### ISSUE TITLE
Sidebar-content class is broken

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#103]
See: https://openframework.stanford.edu/homepage-blocks-demo
About Us block.

It is not floating correctly with the other blocks on this page, probably because it is not in a sidebar region?

**Comment by meganem** [comment]
I am not sure why it is calling up the sidebar-content class styles when this block is not in a sidebar. need to troubleshoot.

**Comment by meganem** [comment]
sidebar-content class seems to be working in first sidebar - try applying to the first sidebar menu block on this page: 
https://sites.stanford.edu/commencement-theming/info/students

**Comment by meganem** [comment]
See about block in footer, which uses sidebar-content class. This is breaking the layout in footer.
https://sites.stanford.edu/commencement-theming/

**Comment by meganem** [comment]
See SHPO site:

https://sites.stanford.edu/shpo/
https://sites.stanford.edu/shpo/about
See contact us block

**Comment by hyperboy** [comment]
The sidebar-first and sidebar-second classes are used in both the body and sidebar div tags.  Renamed sidebar div classes to site-sidebar-first and site-sidebar-second.  See https://github.com/SU-SWS/open_framework/commit/e288f1d454e37178320130ba34aceb166632738b
