### ISSUE TITLE
First time opening menu drawer on mobile does not grab correct height

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#104]
if there are nested links inside, it does not get the correct height the first time.

**Comment by meganem** [comment]
This is still not working:
https://sites.stanford.edu/undergrad-dev/

Just pulled the themes and cleared cache.

**Comment by meganem** [comment]
though I do see it working here: https://openframework.stanford.edu/

So maybe this needs to be implemented in the rest of our theme stack?

**Comment by hyperboy** [comment]
There's a custom page.tpl.php in the undergrad sub-theme.  I've updated the drawer menu code there.  The drawer is now working properly on https://sites.stanford.edu/undergrad-dev/

**Comment by meganem** [comment]
yay! thank you!
