### ISSUE TITLE
/user page accordion is not working

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#105]
I think this is because of the javascript fix you implemented? but if not, then I am not sure.

It works here:
https://sites.stanford.edu/tbdemo/user
(older themes)

but not here:
https://sites.stanford.edu/undergrad-dev/user
(newer themes)

**Comment by meganem** [comment]
Confirmed, this is at OFW level:
https://openframework.stanford.edu/user

**Comment by hyperboy** [comment]
Removed latest jQuery 1.8.2 from /user pages.  See changes in template.php.

  // Update jquery version to 1.8.2 for non-administration pages
  if (arg(0) != 'admin' && arg(0) != 'user' && arg(1) != 'add' && arg(2) != 'edit' && arg(0) != 'panels' && arg(0) != 'ctools') {
    $scripts = drupal_add_js(drupal_get_path('theme', 'open_framework') . '/js/jquery-1.8.2.min.js');
    unset($scripts['core']['misc/jquery.js']);
    $vars['scripts'] = drupal_get_js('header', $scripts);
  }
