### ISSUE TITLE
Cmd+click (Mac OS X) in Firefox does not open link in new tab

### ISSUE THREAD

**Issue by jbickar** [SU-SWS/open_framework#106]
Mac OS X 10.6.8
Firefox 19.0.2

When I Cmd+click on a hyperlink, it should open in a new tab (per browser settings), but it does not. See hyperlinks on https://www.stanford.edu/group/webservices/cgi-bin/video-d7.

So far I have not been able to reproduce this in Safari, Chrome, or Opera - only Firefox. And the behavior is limited only to Open Framework sites (the one linked above and sites.stanford.edu/undergrad-dev), so I don't think it's my Firefox specifically.

**Comment by hyperboy** [comment]
It seems like a Twitter Bootstrap issue: https://github.com/twitter/bootstrap/issues/4535

I'll dig around to see if there's a fix for this.

**Comment by hyperboy** [comment]
See more related issues: 
https://github.com/twitter/bootstrap/issues/7118
https://github.com/milkypostman/melpa/issues/587

**Comment by meganem** [comment]
Known issue in Twitter Bootstrap, we will wait until they fix it.

**Comment by jbickar** [comment]
This was fixed upstream in Firefox (22.0 I think)
