### ISSUE TITLE
Template Clean Up

### ISSUE THREAD

**Issue by oresh** [SU-SWS/open_framework#109]
/tempaltes/*.tpl files clean up.
https://raw.github.com/oresh/open_framework/7.x-2.x/template_clean_up.patch

**Comment by meganem** [comment]
has this patch been incorporated already? if so, close this issue.

**Comment by meganem** [comment]
No we haven't incorporated Kirill's template changes.  The main difference is the way if statements are coded.  
We've also updated the template a bit since Kirill's patch.
