### ISSUE TITLE
html5shiv outdated

### ISSUE THREAD

**Issue by jacobgelling** [SU-SWS/open_framework#118]
html5shiv/html5shim is outdated and the latest version is no longer hosted on google code but instead @ https://github.com/aFarkas/html5shiv/blob/master/dist/html5shiv.js

A problem is we can't just use the following as github only works in https therefore we can't use // as if it is on a http page it just wont work and if we use https:// it may conflict on a http page.

```
<!--[if lt IE 9]><script src="//raw.github.com/aFarkas/html5shiv/master/dist/html5shiv.js"></script><![endif]--> 
```

A possibility is including it within open framework and using <?php print path_to_theme(); ?> but then it would not work with sub themes.

This isn't a too pressing issue as the pre version of html5shiv on google code still works fine.

**Comment by coop182** [comment]
What about using //cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.2/html5shiv.js  ?

**Comment by jacobgelling** [comment]
Yeah, that would work fine.
