### ISSUE TITLE
No Font Awesome IE7 Support

### ISSUE THREAD

**Issue by jacobgelling** [SU-SWS/open_framework#119]
Open Framework has not included font-awesome-ie7.min.css to allow for compatibility with IE7 although the file is included with the download. Personally I would like to have it as IE7 is still (annoyingly) used by some people.

Taken from font awesome homepage:

```
In the <head> of your html, reference the location to your font-awesome-ie7.min.css.

    <!--[if IE 7]>
    <link rel="stylesheet" href="assets/css/font-awesome-ie7.min.css">
    <![endif]-->
```

Obviously it will be need to be adapted to work in Drupal.

**Comment by hyperboy** [comment]
I've added IE7 support for Font Awesome.  See https://github.com/SU-SWS/open_framework/commit/2b3fe71ec971120ca438fdf252cde282f5f464ed
