### ISSUE TITLE
Scaling Disabled

### ISSUE THREAD

**Issue by jacobgelling** [SU-SWS/open_framework#120]
I don't know why but open framework uses:

&lt;meta name="viewport" id="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=10.0,initial-scale=1.0"&gt;

While standard bootstrap uses:

&lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;

Bootstrap's way is better as it allows scaling unlike the open framework.

**Comment by meganem** [comment]
Hi Jacob,
Can you post your examples again, they didn't go through.
Thanks

**Comment by jacobgelling** [comment]
Updated to display properly
