### ISSUE TITLE
Collapsed fields overlap each other

### ISSUE THREAD

**Issue by irinaz** [SU-SWS/open_framework#122]
Hi, 
In chrome/safari closed collapsed fields overlap if all fields are closed.

Here is code that fixed the problem on my site

html.js fieldset.collapsed {
height: auto;
} 

![Screen shot 2013-04-06 at 3 32 56 PM](https://f.cloud.github.com/assets/2497005/347941/2f410d48-9f0c-11e2-9a47-60b71ba0194f.png)

**Comment by meganem** [comment]
Thanks Irina. Confirmed this is in OFW. Not sure if we can make this into tomorrow's release, but we'll get it fixed.

**Comment by irinaz** [comment]
No problem, thanks for dealing with this.  Theme is great!
