### ISSUE TITLE
No upload button in IMCE

### ISSUE THREAD

**Issue by vitcra** [SU-SWS/open_framework#128]
There are not upload buttons in IMCE 7.x-1.7 with open_framework. I discovered that if one uses jquery 1.8.1 instead of 1.9.1, then it works.

**Comment by meganem** [comment]
Thanks for submitting the issue – we will take a look.

**Comment by ghost** [comment]
Similar issue causing the IMCE toolbar not to load at all. Is a simple problem to solve with the following in template.php:

<code>function open_framework_js_alter(&$javascript) {
  // Update jquery version for non-administration pages
  if (arg(0) != 'admin' && arg(0) != 'panels' && arg(0) != 'ctools'  && arg(0) != 'imce') {
    $jquery_file = drupal_get_path('theme', 'open_framework') . '/js/jquery-1.9.1.min.js';</code>

This just simply adds any path for imce to not load jquery-1.9.1 as for admin pages.

**Comment by hyperboy** [comment]
See Related ticket: https://github.com/SU-SWS/open_framework/issues/158
