### ISSUE TITLE
Image uploading issue

### ISSUE THREAD

**Issue by binoykl** [SU-SWS/open_framework#132]
Trying to upload an image using cck field. Though image gets uploaded, that is not getting reflected in the page. the progress icon keeps on rotating.

**Comment by Codelica** [comment]
This should be the same issue that I commented on here:

https://github.com/SU-SWS/open_framework/issues/126#issuecomment-17502845

Basically core's old jQuery Form plugin needs to be updated to work with jQuery 1.9.1 from Open Framework.  The commit linked to my comment there should take care of the problem if the OF maintainers want to take a look.

**Comment by binoykl** [comment]
Thank you. I tried that and it is working, I will run it for a day and then
to production. It added a 0.3 sec delay to the pageload. However, it is
better now. Thank you again
