### ISSUE TITLE
Could i use zengrids with openframework ?

### ISSUE THREAD

**Issue by webmasterpf** [SU-SWS/open_framework#136]
Hi

i'm testind this great base theme for drupal 7, and i would to know if i could use zengrids with it.

it would be a great option, added to tweeter bootstrap (the best for mobile RWD)

grest work

thanks

**Comment by meganem** [comment]
Hi there,
Open Framework has it's own responsive grid system that you can see in action here:
https://openframework.stanford.edu/regions
It utilizes a set of special block regions to drive its responsive patterns. Just place blocks into the region that fits your design goals.
Check out this video for a tutorial on how to build sites using Open Framework:
http://www.youtube.com/watch?v=4IlqcR30wuY

That said, if you make a subtheme of Open Framework, there is nothing stopping you from altering the template files to use Zen grids or any other system you wish to use.

Best,
Megan

**Comment by webmasterpf** [comment]
And what about using sass ? does it linked with twitter bootstrap ?
EDIT : found this that could be the way to use it in openframework

http://thesassway.com/projects/sass-twitter-bootstrap
https://github.com/jlong/sass-twitter-bootstrap

**Comment by meganem** [comment]
Bootstrap is built with Less, not Sass. The Open Framework theme is not built with a pre-processor. That shouldn't stop you from making a subtheme and using whatever CSS preprocessor you like to build your subtheme styles. You can download and access the original Bootstrap Less files from the Bootstrap website if you want somewhere to start.

At the moment we do not have plans to shift Open Framework to use a CSS preprocessor.

**Comment by webmasterpf** [comment]
So i can put the sass version of bootstrap in my sub-theme folder and code css in sass ? and still get advantages of OFW ?
it would be great..
something like adding span and container classes properties to my custom elements via css and don't need to change the html markup...
Actually i try with a custom theme,inside of it , i put a bootstrap sass version folder and create a scss file to do the layout...the same in OFW subtheme is it possible ?

**Comment by meganem** [comment]
It should be! Let us know how it goes.
