### ISSUE TITLE
JS error on 2.04

### ISSUE THREAD

**Issue by webmasterpf** [SU-SWS/open_framework#137]
Hi

Actually testing this base theme, and i get these errors in console :

Uncaught ReferenceError: jQuery is not defined for sites/all/themes/open_framework/js/jquery-migrate-1.1.1.min.js

Uncaught TypeError: Object [object Object] has no method 'on' /sites/all/themes/open_framework/bootstrap/js/bootstrap.min.js

Do i need to enable the openframework base theme ?
Any idea about this issue ?

thanks

**Comment by meganem** [comment]
A couple things -
Open Framework should not be used as an admin theme. Make sure you set Seven or another admin theme on your site. Also, not sure if you are trying to use jQuery update module in conjunction with Open Framework. If so, you should turn off that module as Open Framework takes care of loading its own version of jQuery.

**Comment by webmasterpf** [comment]
ok turning off jquery_update module solve the issue.

**Comment by hyperboy** [comment]
See Related ticket: https://github.com/SU-SWS/open_framework/issues/158
