### ISSUE TITLE
Panels Branch

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/open_framework#142]
Hey Guys,

We have created a fork for our work with OFW and panels: https://github.com/imagex/open_framework and a new branch called 7.x-2.x-panels. Could you create a branch on the SU-SWS account called 7.x-2.x-panels from the current 7.x-2.x branch so that we may send in pull requests for your review and discussion as we work on this version. It is still early in the project for us but I wanted to make sure we got this in front of you as early as possible.

Thanks,
Shea

**Comment by hyperboy** [comment]
Thanks Shea.  I've created the 7.x-2.x-panels branch. See https://github.com/SU-SWS/open_framework/tree/7.x-2.x-panels

**Comment by sherakama** [comment]
Awesome. 

Thanks Brian. We have some more work to do before our first pull request but I wanted to make sure we had this set up. Chat more in detail when the pull request is ready. 

Thanks again,
Shea
