### ISSUE TITLE
jQuery Migrate v1.1.1 plugin causes 404 "Page Not Found" errors in Open Framework 7.x-2.04

### ISSUE THREAD

**Issue by ryanjbonnell** [SU-SWS/open_framework#143]
The bundled version of the jQuery Migrate plugin has an inline comment at the end of the file that causes 404 errors when other minified JavaScript libraries are used in the theme.

Here's the offending line of code in **open_framework/js/jquery-migrate-1.1.1.min.js**:

`//@ sourceMappingURL=dist/jquery-migrate.min.map`

Nearly two months ago, this issue was reported and fixed in jQuery Migrate 1.2.0 ([#33](https://github.com/jquery/jquery-migrate/issues/33), [#34](https://github.com/jquery/jquery-migrate/issues/34)).

Can a newer [or current] version of jQuery Migrate be included in the next release?

For posterity, the following events show up in the Drupal reports at **/admin/reports/dblog**:

```
TYPE: page not found
DATE: Thursday, May 30, 2013 - 16:14
USER: Anonymous (not verified)
LOCATION: http://127.0.0.1/sites/all/themes/open_framework/js/jquery.min.map
REFERRER: 
MESSAGE: sites/all/themes/open_framework/js/jquery.min.map
SEVERITY: warning
HOSTNAME: 127.0.0.1
OPERATIONS: 
```

-–

```
TYPE: page not found
DATE: Thursday, May 30, 2013 - 16:14
USER: Anonymous (not verified)
LOCATION: http://127.0.0.1/sites/all/themes/open_framework/js/dist/jquery-migrate.min.map
REFERRER: 
MESSAGE: sites/all/themes/open_framework/js/dist/jquery-migrate.min.map
SEVERITY: warning
HOSTNAME: 127.0.0.1
OPERATIONS: 
```

As an example, if using **jquery.validate.min.js**, the opening lines include the following multiline comment:

```
/*! jQuery Validation Plugin - v1.10.0 - 9/7/2012
https://github.com/jzaefferer/jquery-validation
Copyright (c) 2012 Jörn Zaefferer; Licensed MIT */
```

When combined together, this causes a JavaScript error as it is evaluated like this:

```
//@ sourceMappingURL=dist/jquery-migrate.min.map /*! jQuery Validation Plugin - v1.10.0 - 9/7/2012
https://github.com/jzaefferer/jquery-validation
Copyright (c) 2012 Jörn Zaefferer; Licensed MIT */
```

Tested using Drupal v7.22 with Open Framework 2.04.

**Comment by hyperboy** [comment]
Thank you for the detailed testing and explanation.  I've added jquery-migrate-1.2.1.min.js to the 7.x-2.x branch.  The change will be incorporated in the next tagged release.

**Comment by agold2** [comment]
Patch against 7.x-2.04 for drush make file https://gist.github.com/agold2/5710532
