### ISSUE TITLE
Regions are included twice in subtheme_kit

### ISSUE THREAD

**Issue by gitressa** [SU-SWS/open_framework#146]
I thought I remembered an issue about the order of regions being fixed at some point, so I couldn't understand why the "Footer" regions was up in the beginning again, why "Main: Top" was below the sidebars, etc. But when I looked in subtheme_kit it all made sense: Some regions were included twice.

These are all the region defintions in the subtheme_kit.info file, I have commented out the extra regions that need to be deleted with "; "

; regions[header] = Header
; regions[login_box] = Login Box
; regions[navigation] = Navigation
; regions[search_box] = Search Box
; regions[highlighted] = Highlighted
; regions[help] = Help
; regions[sidebar_first] = First sidebar
; regions[sidebar_second] = Second sidebar
; regions[footer] = Footer

regions[admin_shortcuts] = Admin Shortcuts (Authenticated Users Only)
regions[header] = Header
regions[navigation] = Navigation
regions[search_box] = Search Box
regions[main_top] = Main: Top
regions[main_upper] = Main: Upper
regions[sidebar_first] = First sidebar
regions[highlighted] = Highlighted
regions[help] = Help
regions[content_top] = Content: Top
regions[content_upper] = Content: Upper
regions[content] = Content: Body
regions[content_row2] = Content: 2-column flow
regions[content_col2-1] = Content: 2-column stacked (1)
regions[content_col2-2] = Content: 2-column stacked (2)
regions[content_row3] = Content: 3-column flow
regions[content_col3-1] = Content: 3-column stacked (1)
regions[content_col3-2] = Content: 3-column stacked (2)
regions[content_col3-3] = Content: 3-column stacked (3)
regions[content_row4] = Content: 4-column flow
regions[content_col4-1] = Content: 4-column stacked (1)
regions[content_col4-2] = Content: 4-column stacked (2)
regions[content_col4-3] = Content: 4-column stacked (3)
regions[content_col4-4] = Content: 4-column stacked (4)
regions[content_lower] = Content: Lower
regions[content_bottom] = Content: Bottom
regions[sidebar_second] = Second sidebar
regions[main_lower] = Main: Lower
regions[main_bottom] = Main: Bottom
regions[footer] = Footer

**Comment by meganem** [comment]
Thanks for catching that!

**Comment by gitressa** [comment]
You're welcome, thanks for making such a kick-ass theme :-)

I hope some day to see it on drupal.org, are you getting closer to set a date for that?

**Comment by meganem** [comment]
Thanks! We would really like to, but it's moved a little lower on our priorities list. We are planning a next release (see issues in V2 milestone) for early August. Then I think at that point we can think about what it takes to get it on drupal.org. There is a licensing issue with including Bootstrap, so that's one thing we have to deal with.

**Comment by gitressa** [comment]
You're right, the license issue is a bit of a challenge... I hope you get it solved eventually, have a nice summer!
