### ISSUE TITLE
Undefined index: scope in drupal_get_js()

### ISSUE THREAD

**Issue by deburca** [SU-SWS/open_framework#147]
Notice: Undefined index: scope in drupal_get_js() (line 4238 of /app/www/html/eibsites/hubdev/includes/common.inc).

In template.php, version 1.9.1 of jQuery replaces the Drupal standard jQuery with

```
$javascript['misc/jquery.js']['data'] = $jquery_file;
$javascript['misc/jquery.js']['version'] = $jquery_version;
$javascript['misc/jquery.js']['weight'] = 0;
$javascript['misc/jquery.js']['group'] = -101;
```

However, the following line should be added to add the scope of the script

```
$javascript['misc/jquery.js']['scope'] = 'header';
```

Once added, the above notice disappears :-)

**Comment by deburca** [comment]
To avoid other notices of undefined indexed, I ended up copying the defaults from common.inc

```
    'misc/drupal.js' => array(
      'data' => 'misc/drupal.js',
      'type' => 'file',
      'scope' => 'header',
      'group' => JS_LIBRARY,
      'every_page' => TRUE,
      'weight' => -1,
      'preprocess' => TRUE,
      'cache' => TRUE,
      'defer' => FALSE,
    ),
```

to template.php - as follows

```
$javascript['misc/jquery.js']['data'] = $jquery_file;
$javascript['misc/jquery.js']['type'] = 'file';
$javascript['misc/jquery.js']['scope'] = 'header';
$javascript['misc/jquery.js']['group'] = -101;
$javascript['misc/jquery.js']['every_page'] = TRUE;
$javascript['misc/jquery.js']['weight'] = 0;
$javascript['misc/jquery.js']['version'] = $jquery_version;
$javascript['misc/jquery.js']['preprocess'] = TRUE;
$javascript['misc/jquery.js']['cache'] = TRUE;
$javascript['misc/jquery.js']['defer'] = FALSE;
```

**Comment by deburca** [comment]
Hit close by accident. Sorry.

**Comment by meganem** [comment]
Thanks Paddy!

**Comment by hyperboy** [comment]
Thanks for the research!

**Comment by Codelica** [comment]
Hello,

I don't believe this was needed, and actually may effect the output order of the jQuery inclusion.  The call being used here is an alter call (hook_js_alter()) so the initial Drupal settings from common.inc should still be in place.  If they aren't, then some other module has modified them before Open Frameworks alter call.  I have a feeling that the jQuery Update module does this. @deburca do you have the jQuery Update module installed by chance?

**Comment by hyperboy** [comment]
James, Thanks for the feedback.

**Comment by deburca** [comment]
James, yes I do have jQuery Update installed - as a dependency of some other modules. When adding the extra values, I used the Drupal defaults for /misc/jquery.js - and as we are replacing jquery.js with a newer version, the defaults should remain the same.

I will see what I can do to improve the code when jquery update module is installed.

**Comment by Codelica** [comment]
This issue actually comes up quite often.  There seems to be a few ways to go:

**1) Wrap the original (pre-commit) alter code with a conditional that checks if jQuery Update is installed and active.  If it is then the OFW alter is bypassed.**  

**Pros:**  No errors for anyone, jQ Update or not.
**Cons:** People are now potentially using OFW with various versions of jQuery.

**2) Make OFW require jQuery Update and require the latest version to be active.**  

**Pros:** Everyone is using the same version of jQuery.
**Cons:** jQuery Update is slow to update and still contains an old version.

**3) Require that OFW does the jQuery upgrade, showing a warning if jQuery Update is installed and activated.**

**Pros:** OFW in control and everyone using the latest version of jQuery.
**Cons:** A problem for people using other modules that require jQuery Update.

Personally, I think (1) is probably the best compromise. People will just have to understand that the most supported version comes with letting OFW do the replacement, at least until jQuery Update offers later versions.

**Comment by hyperboy** [comment]
See Related ticket: https://github.com/SU-SWS/open_framework/issues/158
