### ISSUE TITLE
Why isn't this on Drupal.org

### ISSUE THREAD

**Issue by mgifford** [SU-SWS/open_framework#148]
Curious why you don't have this as a project mirrored on Drupal.org? Makes thinks easier to coordinate.

**Comment by meganem** [comment]
Hi Mike,
It is our intention to eventually get this up on drupal.org, but right now we are prioritizing the work for the next release which will take place this August. There are some issues to sort out regarding the licensing conflict between drupal.org and Twitter bootstrap, and some other considerations that we are balancing. We will definitely let everyone know when we have a timeline for d.org!

**Comment by mgifford** [comment]
This totally makes sense. Thanks!

**Comment by ghost** [comment]
It's almost a year later and I notice it still isn't on drupal.org.  There are a number of Twitter bootstrap themes there, so I have to believe the licensing issue must have been worked out.  Some of my clients are reluctant to use modules/themes that aren't hosted via drupal.org.

Any idea when?
