### ISSUE TITLE
Terms of Usage and Production

### ISSUE THREAD

**Issue by SNaushadS** [SU-SWS/open_framework#149]
Hi,

I fortunately stumbled upon this theme while googling for Drupal Bootstrap. While going through Terms of Use at this link: https://drupalthemes.stanford.edu/terms-use.
The term says:

> Use of the Stanford-branded themes is limited to Stanford University academic and > > > administrative activities. Use is granted solely to:
> 
> University academic departments, centers and research groups;
> University administrative units;

I am confused regarding the usage, can we actually use this theme on non-academic commercial production drupal sites ?

Also, is this theme production ready with the necessary features ? I am aware that the development is ongoing and its progressing. I just want this info to be sure to use it for my project.

NB: Im not a programmer, i just love using Drupal and other CMS solve problems.

Thanks.

**Comment by meganem** [comment]
Ooops, that is probably our fault. We use this theme as the base theme for all Stanford-branded themes, and the terms of use for the Stanford-branded themes must have been accidentally copied down to Open Framework.  We'll get that updated asap.

**Comment by meganem** [comment]
So, just to be clear, Open Framework is available for all to use. It's the Stanford-branded themes that are not.

**Comment by SNaushadS** [comment]
Thanks for the clarification.
