### ISSUE TITLE
On Mobile, Smartphone Menu-Button is not clickable

### ISSUE THREAD

**Issue by ghost** [SU-SWS/open_framework#150]
I installed the Theme.
I have testet the fresh install on Smartphone/Android - FF and Opera.

The Menu collapses, but when i push the button to activate the menu - Nothing happens.
Maybe i make a mistake?

Thx for help

**Comment by ghost** [comment]
Hm, cleaned the Cache a couple of times with drush.
And now it works.

Btw: This is a fantastic Theme.
Thx for that

**Comment by meganem** [comment]
Thanks Bernie!
Glad you got it figured out. Yeah.. when in doubt... clear the cache! :)
