### ISSUE TITLE
jQuery 1.9.1 breaks jquery ui shipped with Drupal.

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/open_framework#152]
The packaged version of jQuery has compatibility issues with jQuery ui that is in Drupal. 

Please see for some more information: https://github.com/imagex/open_framework/pull/16

**Comment by ghost** [comment]
Thx ...
Could this be the reason why date-popup from the date-module has no functionality with ofw at the moment.
Changing the theme - Everything is ok.

**Comment by meganem** [comment]
Hi all, we're working on a more robust fix for this. As a rule, you should not use Open Framework as an admin theme. Use something like Seven instead. Also, right now the theme has conflicts with jQuery update. I think Brian has a plan for how to resolve this.

**Comment by hyperboy** [comment]
See Related ticket: https://github.com/SU-SWS/open_framework/issues/158
