### ISSUE TITLE
Getting Started with the Theme

### ISSUE THREAD

**Issue by SNaushadS** [SU-SWS/open_framework#153]
Hello,

Firstly i would like to appreciate the speed at which this theme is being worked upon.

I am considering to use Open Framework sub theme instead of Omega for my Drupal 7 site.

The only reason i am considering this is because of Bootstrap, Bootstrap in itself is amazing and i wish to leverage its power.

However, i am a budding developer and have no coding experience in Drupal, i love the way we can add regions to Omega theme by going into .INFO file and then change them with Delta and Contexts.

Kindly guide me in below areas:
1. How do we add regions to a OFW sub-theme ?
Please let me know the details Or point me to some resource.
1. Can we achieve similar theme modifications (like altering region widths and placements) in OFW with Delta and Contexts ?
   If there is some other way to do it, please let me know.
2. Lastly, is this theme production ready ?

From the documentation and How To use section i understand that it works well with Bean, Block Class

Thank you for taking time to read this. I don't code, but i love OpenSource and appreciate your contribution towards it.

**Comment by hyperboy** [comment]
Hi SNaushadS, 

Thank you for using Open Framework.  It is possible to do the things you want if you create an OFW sub-theme.
1. Locate the subtheme_kit directory within open_framework.  Follow the instructions on README.txt
2. Add additional theme regions to the .info file in your sub-theme.
3. Copy the templates/page.tpl.php from open_framework to your sub-theme, keeping the directory structure the same as the base theme.  The template files in your sub-theme will override the ones in the base theme.

Open Framework works well with Delta and Context for region content placement.  For region widths, you'll need to modify the page.tpl.php in your sub-theme.  For example, you can modify the sidebar region widths from span3 to span4 by changing the following:

```
<div id="sidebar-first" class="sidebar span3 site-sidebar-first">...</div>
<div id="content" class="mc-content <?php if (($page['sidebar_first']) && ($page['sidebar_second'])): print 'span6'; elseif (($page['sidebar_first']) || ($page['sidebar_second'])): print 'span9'; else: print 'span12'; endif; ?>">...</div>
<div id="sidebar-second" class="sidebar span3 site-sidebar-second">...</div>
```

to

```
<div id="sidebar-first" class="sidebar span4 site-sidebar-first">...</div>
<div id="content" class="mc-content <?php if (($page['sidebar_first']) && ($page['sidebar_second'])): print 'span4'; elseif (($page['sidebar_first']) || ($page['sidebar_second'])): print 'span8'; else: print 'span12'; endif; ?>">...</div>
<div id="sidebar-second" class="sidebar span4 site-sidebar-second">...</div>
```

You may need to add another override.js in your sub-theme to override the responsive behaviors of the theme regions.

Open Framework is production ready and is used as the base theme for Stanford sites like http://itservices.stanford.edu, http://commencement.stanford.edu and http://undergrad.stanford.edu.  It lacks the features and UI refinements of the more established themes like Omega and Zen, but we're working to improve that.
