### ISSUE TITLE
Resizing window doesn't work 

### ISSUE THREAD

**Issue by riteshgurung** [SU-SWS/open_framework#154]
## Environment:

OS: Linuxmint
Browser: Chrome
Version: Version 28.0.1500.71
## Usecase Scenario:

Browse through the site : https://drupalthemes.stanford.edu/stanford-wilbur

Resize the browser window manually to the point where you can see only only coloumn. Maximize the browser window. The contents/viewport is not resized accordingly.

**Comment by ghost** [comment]
Hello,
I have Linuxmint 15/64 // Chrome always the newest Version.
I cant confirm.

I resized to one column and back to maximize.
Everything is ok.

One thing:
I dont have any extensions in Chrome installed. 
Just a fresh install.

Hope this helps

**Comment by meganem** [comment]
Thanks for checking Bernie. We haven't seen this problem either.
