### ISSUE TITLE
Content First on mobile devices

### ISSUE THREAD

**Issue by ghost** [SU-SWS/open_framework#155]
Hello,
Ofw has a lot of cool features. So thx for that.
At the moment i have problem with the three column layout.

For example on Desktop everything is standard.

Sidebar left  Content  Sidebar right.

But on mobile devices i need the Content first. 
I have not yet found a solution.

What did I miss?
How can i achieve One-Column-Layout with Content first.

Thx for your efforts

**Comment by hyperboy** [comment]
You can leverage the display:flex CSS property to reorder the sidebar and center content in mobile.

Try the following CSS:

```
@media (max-width: 767px) {
    .main-content {
        display: -webkit-box;
        display: -moz-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -webkit-box-orient: vertical;
        -ms-flex-direction: column;
        -webkit-flex-direction: column;
        flex-direction: column;
    }
    .mc-content {
        -webkit-box-ordinal-group: 1;  
        -moz-box-ordinal-group: 1;     
        -ms-flex-order: 1;
        -webkit-order: 1; 
        order: 1;
    }
    .site-sidebar-first {
        -webkit-box-ordinal-group: 2;  
        -moz-box-ordinal-group: 2;     
        -ms-flex-order: 2;
        -webkit-order: 2; 
        order: 2;
    }
    .site-sidebar-second {
        -webkit-box-ordinal-group: 3;  
        -moz-box-ordinal-group: 3;     
        -ms-flex-order: 3;
        -webkit-order: 3; 
        order: 3;
    }
}
```

**Comment by ghost** [comment]
Thx, I will give it a try. 
Because this is for a newspaper/magazine and the Content should come first.

**Comment by ghost** [comment]
So a big thx, hyperboy,
Now i have the Content First and everything works as expected.

**Comment by hyperboy** [comment]
Great!  I've documented it on https://openframework.stanford.edu/content-first-responsive-layout
