### ISSUE TITLE
Empty/Null ARIA landmark between content and footer

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#159]
"In general, the page makes good use of HTML5 and ARIA landmarks to identify structural areas and navigation. However, there is an ARIA property that appears to be used as a separator between the main content and the footer that JFW reports as an ""empty article landmark."" This might be confusing to screen reader users because ARIA landmarks generally identify sections of the page that contain content, e.g., navigation, search, article, etc., not empty content."

Also in SUFW etc.

**Comment by jbickar** [comment]
This referred to https://undergrad.stanford.edu. I will try to find the incorrect landmark.

**Comment by jbickar** [comment]
Can't find it; will have to ask Jennifer.

**Comment by jbickar** [comment]
node.tpl.php is using the &lt;article&gt; element to wrap node content. When we use empty nodes for pages (e.g., on home pages), JFW reports the empty article element as an empty ARIA landmark. Which, I think, it shouldn't. Maybe.

http://www.w3.org/WAI/PF/aria-implementation/#mapping_role_table
http://www.w3.org/TR/wai-aria/roles#article

I'll submit a ticket to TPG helpdesk.

**Comment by jbickar** [comment]
TPG says the best solution is to not output the &lt;article&gt; element if it is empty, as it carries semantic meaning: https://tpg.opquast.com/en/helpdesk/deliveries/802

I think we have two options:
- Add logic to node.tpl.php (or a level above) to not output the node content if it is empty
- Change the &lt;article&gt; element to a &lt;div&gt; element, and lose some semantic meaning.

Brian, thoughts?

**Comment by jbickar** [comment]
Actually, we also could create a page for use as the home page that is not a node. But this problem will persist any time we have a node with no content.

**Comment by meganem** [comment]
I think with the way we build features as views blocks, and with our many landing pages, we are going to need a solution that fixes this generally.

**Comment by jbickar** [comment]
I agree.

From TPG:

> The mapping of the article element to the article role is defined in the HTML specification.
> 
> In ARIA the article role is not defined as a landmark, but JAWS has implemented it as such. In any case the inclusion of empty elements that expose semantics to end users is not good practice and can lead to the situation you document. we strongly recommend that you follow the advice you outlined for the article element and extend it to any of the structural elements that expose semantics to the end user:
> 
> >    Add logic to the page template to only display the article element if it contains article content
