### ISSUE TITLE
Fix accessibility issues with site search box

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#161]
How should the search button be modified throughout the theme (e.g., the current button isn’t labeled for screen reader use)? Is it ok that the button is just using an image, and not text?
Example: http://undergrad.stanford.edu
Drupal - How do we add alt text to the search image via a preprocess function?

**Comment by jbickar** [comment]
I think this is the same issue:
https://github.com/SU-SWS/open_framework/issues/115

**Comment by meganem** [comment]
closing as duplicate.
