### ISSUE TITLE
Not respecting responsive sizing on iPad after orientation change

### ISSUE THREAD

**Issue by nthird** [SU-SWS/open_framework#165]
I have a site using a custom theme based on open framework.  When loaded on an iPad running version 5.5.1 in landscape mode it correctly respects the responsive design.  When rotated to portrait mode it correctly changes to the correct design for that size.  However, when rotated back to landscape mode it no longer respects the responsive design and instead tries to load with the design as if it is being viewed on a desktop.  Has anyone else experienced problems with this and found any sort of solution?  I suspect that when it refreshes it for the orientation change it is briefly triggering off of erroneous screen size data.

**Comment by meganem** [comment]
I have seen this before, but not just with OFW. I have not specifically tested this to figure out if it is in the theme, or just mobile browser behaviors, and whether there is a way to fix it.
