### ISSUE TITLE
Can't override span for main content

### ISSUE THREAD

**Issue by keneim** [SU-SWS/open_framework#167]
In my subtheme's page.tpl.php file I altered 
if (($page['sidebar_first']) && ($page['sidebar_second'])): print 'span6';
to read
if (($page['sidebar_first']) && ($page['sidebar_second'])): print 'span7';

However, the html now shows  class="mc-content span7 span6">

Not sure where that "span6" is coming from. Before I edited it, only one span class was being included. But after altering it, it puts out the new span class, but then overrides that with the original.

**Comment by hyperboy** [comment]
The "span6" is coming from /js/override.js.  Add an override.js in your sub-theme to set up your custom theme specific responsive behaviors.

**Comment by keneim** [comment]
Hmmm. Interesting that the sidebar span classes I altered in the page.tpl file did not get overridden. Anyway, Thanks. I'll take a look at override.js.
