### ISSUE TITLE
Conflict with Media module

### ISSUE THREAD

**Issue by matthewgann** [SU-SWS/open_framework#169]
First, great work!

Problem: There's a conflict somewhere with the Media module (multiple versions) and open_framework.  

Media's output error:
Uncaught TypeError: Cannot read property 'Drupal' of undefined 

Stemming from:
var selected = this.contentWindow.Drupal.media.browser.selectedMedia

Thanks for the great work!

**Comment by shanebee** [comment]
Are you still having this problem? I use Media on a few sites that I plan on upgrading to Open Framework.

**Comment by matthewgann** [comment]
It's solved with the latest version when used with jquery_update.

-mg

On Nov 29, 2013, at 2:25 PM, "Shane Birley" <notifications@github.com<mailto:notifications@github.com>> wrote:

Are you still having this problem? I use Media on a few sites that I plan on upgrading to Open Framework.

##
