### ISSUE TITLE
Search_box is not apprearing

### ISSUE THREAD

**Issue by saptha** [SU-SWS/open_framework#175]
Hi

in the version 2.05 when I enabled the block search form in search_box region
its not getting displayed

Regards
Saptha

**Comment by meganem** [comment]
We'll need to test this again. I don't think we were having any problems like this. Are you using the standard block region placement, or are you using Context or something else?

**Comment by saptha** [comment]
Yes I'm using the standard block region

**Comment by rahuldudeja-zz** [comment]
It might be a permission related issue...please verify that the search
module has view permissions.

## 

Regards
Rahul

**Comment by saptha** [comment]
Yes it has view permissions. Please note that the Search form is not appearing only when placed in search_box region whereas if I place it in other regions like Side bar or header it is visible properly.

**Comment by saptha** [comment]
Today I found that the search box is appearing in the smartphone displays. But not in desktops. Would that be an issue with css

**Comment by meganem** [comment]
Hi Saptha, We don't see this happening in any of our dev sites. It's possible that you may have introduced something via CSS. Bootstrap does have several "hidden-desktop" type classes available (see this page: http://getbootstrap.com/2.3.2/scaffolding.html#responsive). Perhaps see if you can inspect the code on Desktop to see whether the search box is there, being rendered with HTML, but then hidden with CSS. I'm sorry we can't be more of a help, but this doesn't seem like a reproducible error.

**Comment by saptha** [comment]
Finally I figured it out. It is with the margin defined in the following css.
.nav-search {
        float:right;
        margin:-65px -20px 0 0;
        padding:0;
        min-height:1px;
}

I changed the margin definition and it displayed properly.
Earlier I had modified the page.tpl.php in my subtheme to suit my needs.
