### ISSUE TITLE
Compressed image assets. 

### ISSUE THREAD

**Issue by rwinikates** [SU-SWS/open_framework#176]
I ran the two images from the /images/ directory through kraken.io, so that we can serve the most optimized (i.e. smallest) files possible.  
![searchbutton](https://f.cloud.github.com/assets/533947/913273/9923624a-fe13-11e2-9131-386c4c2ef6a4.png)
![ofw-more-link-arrows](https://f.cloud.github.com/assets/533947/913274/9926ed84-fe13-11e2-8c30-df5afb149b8b.png)

These compressed images save almost 90% of the file size (dropping from 4.11k to just 431b).  I realize saving 3k seems silly, but hey, why not, right?

**Comment by hyperboy** [comment]
Very cool!  I've updated searchbutton.png and ofw-more-link-arrows.png in the /images/ directory.  Thanks for contributing!

**Comment by saptha** [comment]
How about using the Glyphicons class="icon-search" as per the link http://getbootstrap.com/2.3.2/base-css.html#icons.
But I don't know how to include this in $form['actions']['submit'] in template.php
