### ISSUE TITLE
Doesn't work properly with FullCalendar

### ISSUE THREAD

**Issue by rmanola** [SU-SWS/open_framework#177]
When using the fullcalendar library with fullcalendar drupal module (https://drupal.org/project/fullcalendar) the events get out of position after resizing, also the last day on the right gets squeezed.

**Comment by meganem** [comment]
When using custom modules, it is very likely you will need to do a little custom style work to get them to display properly, as we can't guarantee that our theme supports all custom module code.

**Comment by rmanola** [comment]
Every drupal theme that I have tested (more than 10) support fullcalendar without problems. I guess this should be marked as "Feature Request".

**Comment by meganem** [comment]
If you can create a block of CSS that supports it, or find the reasons why it is breaking, please submit a pull request, or just send us your code so we can integrate it. Thanks!
