### ISSUE TITLE
Nested images not accounted for when div.column height is set on page reload

### ISSUE THREAD

**Issue by aaroncole** [SU-SWS/open_framework#178]
On initial page load, the height all div.column elements are set to match the tallest in the current row.  On page reload, however, nested images are not taken into account and the height of these elements are set too short.

The issue and solution are outlined here:
http://drupal.stackexchange.com/questions/77329/javascript-running-before-page-fully-loaded#answer-77330

![grid_height_bug](https://f.cloud.github.com/assets/465014/925008/7982d1a4-ff72-11e2-877f-4dced08a002b.png)

**Comment by hyperboy** [comment]
See e58b275c85a5fae2fdb60801b4bd6bdfbd9cf86c
