### ISSUE TITLE
Need theme options to support logo image behavior in mobile view 

### ISSUE THREAD

**Issue by hyperboy** [SU-SWS/open_framework#18]
Provide option to display logo image in mobile view.  This gets tricky for sites with large logo/banner images.  Perhaps provide theme options to accommodate the different logo image sizes.

**Comment by meganem** [comment]
megan wireframe some solutions for this?

**Comment by hyperboy** [comment]
I'll add a theme option for logo image behavior.

**Comment by meganem** [comment]
Would be nice to have an optional "upload mobile logo" theme option, that lets you load a different version of the logo for mobile viewing.

To be clear, this issue is for when people have disabled Drupal's site title and slogan and are only using the logo as their visible site title.

**Comment by meganem** [comment]
UPDATE:

By default, have logo stack on top in mobile (DONE).
Add theme option for alternate mobile logo file. (OPTIONAL - NOT DONE)
Add theme option to hide logo when in mobile view, and only show site title. (NOT DONE)

**Comment by meganem** [comment]
done a while ago! :)
