### ISSUE TITLE
Change more-link to use CSS not image, and adjust styles

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#183]
a.more-link:after {
    content: " »";
}

a.more-link {
    display: inline-block;
    line-height: 1.2em;
    margin-bottom: 0.5em;
    margin-top: 0;
}

and remove the image and padding that supports the image

**Comment by meganem** [comment]
Make sure to test upstream on client sites and custom sites, and change in all subthemes.

**Comment by meganem** [comment]
@hyperboy did you also update all our subthemes for this? I didn't make separate github tickets for Stanford Framework. (I don't think we have specific styles in Wilbur and Jordan, but I know we do in SUFW).

**Comment by hyperboy** [comment]
I'll add an issue in SUFW and sub-themes if needed.  Thanks.
