### ISSUE TITLE
Radio Buttons Formatting

### ISSUE THREAD

**Issue by shanebee** [SU-SWS/open_framework#187]
I have been testing 2.05 for the past few days and I have noted that radio buttons are now pushing the text to the next line. I thought it was something I did so I reset the theme back to the starter kit defaults but the behaviour still is present.
![2013-08-20 10_40_14-radiobuttons](https://f.cloud.github.com/assets/313916/995531/efdd46ac-09bf-11e3-8a00-bfe9607f1d40.png)

**Comment by samrose** [comment]
I typically have to assign a "float: left" on these form elements in my css of my subtheme. The theme simply does not address this display element. And, maybe it should not?

**Comment by shanebee** [comment]
I agree. Having the Open Framework theme address every single format requirement could lead to overly bloated CSS.

**Comment by samrose** [comment]
I've started to create my own subtheme baselines with these tweaks and the baseline CSS file repo can be included in your site make file for instance. I can do the same baseline and comment out for media queries etc. in the end, the final CSS and HTML structure for a site are usually different on a case by case basis, so I truly believe it is better for open framework to not address these elements, and let themers mold and shape as needed.
