### ISSUE TITLE
Why are we specifying float-right styles for row-fluid??

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#189]
Hi Brian,
I want to remove the lines in OFW that are specifying styles for float-right in regions marked as row-fluid, since all our regions are row-fluid now (right?) and I'm getting overriden styles which are removing my left margin I need on floated images/content.

Can I remove these lines?
741 (just the line about row-fluid float-right not having a left margin (which it should))
1042-1044 (seems conflicting with lines 735-737 )

OR, do I need to add the left margin back at these lines:
1045-1048

I am just wondering why we have this complicated setting/unsetting of this particular CSS around the row-fluid. Are we using float-right in a special way for that region type?

**Comment by meganem** [comment]
Here's an example: https://sites.stanford.edu/ipaw-2013-08/royal-image-portraits-satires-and-life-court-2

**Comment by hyperboy** [comment]
I think the float-right styles were intended for blocks, hence all the margin complications.

We should probably be more explicit in our CSS, we should be useing[.row-fluid .block.float-right] instead of [.row-fluid .float-right].

I've reverted the open_framework.css back to single line formatting.  Refer to lines 244-247 and 317-318.

**Comment by meganem** [comment]
Um, actually I think we need to be less specific. Just using .float-right alone. We use these classes in the WYSIWYG prominently for floating images left and right, and don't really use them anywhere else (though they should be able to be used elsewhere). So, if we need specific float-right styles without left margins for blocks, then we should augment a default .float-right definition.

**Comment by meganem** [comment]
.float-right { float:right; margin-left:15px; }
.block.float-right { margin-left:0px; }

**Comment by meganem** [comment]
You should use Bootstrap's pull-left and pull-right for more "pure" float classes, whereas we will keep the float-right and float-left classes for use in the WYSIWYG since we use that EVERYWHERE.
