### ISSUE TITLE
Open Framework (Twitter Bootstrap and jQuery 1.7.1) Javascript component is disabled by default

### ISSUE THREAD

**Issue by hyperboy** [SU-SWS/open_framework#19]
jQuery 1.7.1 has conflicts with the Drupal 6 blocks layout page as well as the Stanford course import module.

**Comment by meganem** [comment]
Is this just a 6.x problem, or also a 7.x problem, and is it related to our main issue of jquery conflicts between Twitter Bootstrap and Drupal?

**Comment by hyperboy** [comment]
It should not be an issue in D7 anymore.  jQuery 1.9.1 will now load only on non-admin pages.  I will need to test it with the Stanford course import module though.  Haven't made any changes to the D6 theme.
