### ISSUE TITLE
Missing "scope" index from hook_js_alter()

### ISSUE THREAD

**Issue by stefano73** [SU-SWS/open_framework#190]
Got this warning:
Notice: Undefined index: scope in drupal_get_js() (line 4266 of /home/stefano73/drupal7/includes/common.inc).

I got it fixed by setting the JS defaults in function open_framework_js_alter():
<code>$javascript['misc/jquery.js'] = drupal_js_defaults();</code>

**Comment by hyperboy** [comment]
We've implemented a smarter way of doing jquery versioning in our 2.05 beta. Try it out and see if it fixes your problem. https://github.com/SU-SWS/open_framework/releases/tag/7.x-2.05-beta
