### ISSUE TITLE
Unset jQuery loaded by jQuery update module

### ISSUE THREAD

**Issue by stefano73** [SU-SWS/open_framework#191]
When jQuery Update module is enabled, you have two jQuery instances in your page. So I guess that open_framework should unset the one from jQuery Update, if present.
Got it fixed by adding these lines in function open_framework_js_alter():
<code><pre>
if (module_exists('jquery_update') && $version = variable_get('jquery_update_jquery_version', '')) {
      unset($javascript[drupal_get_path('module', 'jquery_update').'/replace/jquery/'.$version.'/jquery.js']);
}
</pre></code>

**Comment by hyperboy** [comment]
We've implemented a smarter way of doing jquery versioning in our 2.05 beta. Try it out and see if it fixes your problem. https://github.com/SU-SWS/open_framework/releases/tag/7.x-2.05-beta
