### ISSUE TITLE
Issue with theme.inc

### ISSUE THREAD

**Issue by saptha** [SU-SWS/open_framework#193]
Hi
I get the below error while the cron job related to a particular drupal module epub_export is being run.
Warning: array_key_exists() [function.array-key-exists]: The first argument should be either a string or an integer in ThemeRegistry->offsetExists() (line 421 of /home/pub/includes/theme.inc

Whereas this module is working fine with other twitter bootstrap themes for drupal.
Any idea?
Thanks & regards
Saptha

**Comment by hyperboy** [comment]
Unfortunately we don't use the epub_export module and won't have the bandwidth to test and fix the theme.inc problem.
