### ISSUE TITLE
.row on #main-content not removing left margin

### ISSUE THREAD

**Issue by shanebee** [SU-SWS/open_framework#194]
I think this is a duplicate of other issues but I can't seem to match what I am seeing.

The main content container has a row class assigned to it but it doesn't seem to remove the left margin.

Am I crazy or is this happening?

**Comment by meganem** [comment]
We are able to recreate this, it happens when you place multiple blocks (esp. with spans) in the main content region, and they aren't correct margins (or something like that). Brian will take a look

**Comment by shanebee** [comment]
Just a quick note: I worked around it (this is running on the 2.05-beta tagged, not 2.04) by adding a negative margin to the left side of the column and it didn't blow anything up.

And let me be the first to say, that you all kick ass. Open Framework has introduced a few of my employees to a system of responsive theme development that doesn't break their brains.

**Comment by meganem** [comment]
Shane, That is so nice to hear! Thanks for the feedback!

Just so you know, this issue isn't probably going to make it into our next tagged release, but a work-around for right now is to use another region, like the content-upper or content-lower regions to do custom block/span layouts.

**Comment by shanebee** [comment]
Just a quick addendum, this still needs fixing, yes -- but I noted in the cascade order that the #content div automatically has a span12 class on it. I simply added a zero margin and padding on that div by itself and the issue was fixed.

Haven't dug that far into it but it worked just yesterday and was a small happy accident.

**Comment by hyperboy** [comment]
The #main-content region behaves differently from the other block regions.  It is intended for body content.  Try placing your blocks in the content-top or content-lower block regions.
