### ISSUE TITLE
Make SASS/LESS CSS pre-process files available

### ISSUE THREAD

**Issue by ghost** [SU-SWS/open_framework#195]
I've recently started using SASS as my CSS pre-processor of choice and have become quite ennamoured of it.

Would it be likely/possible for 7.x-2.05 of OFW to include the full SASS/LESS sources? I think it might benefit a lot of users.

This should be labeled as a Feature Request.

Regards
Andrew

**Comment by meganem** [comment]
Hi Andrew,
We currently do not use a preprocessor to create Open Framework CSS. There's an issue #63 and this is something we are strategizing about for our roadmap for the theme, but it's not possible at this time.
