### ISSUE TITLE
Some bad things happen

### ISSUE THREAD

**Issue by ghost** [SU-SWS/open_framework#196]
Hi Folks,

Since we are working with ofw the generating-time of the site needs up to 20 sec.
Since yesterday the site shows a 503 with ofw.

When i change to "Bartik" or "Garland" everything is normal. The site shows up in 2 Seconds. This only happens with ofw.

Do you have an idea what can cause the problems with ofw?

**Comment by ghost** [comment]
... and now i found out that the problem occurs in Fullview, when someone wants to read an article.
So generating the node takes too long.

**Comment by ghost** [comment]
... And now i tested that with the main Openframework Theme. Everything is ok.
It only happens with the Sub-Theme.

**Comment by meganem** [comment]
Hi Bernie,
Sorry you're having trouble with your subtheme. I'm closing this issue, as it's not clear to me this is a problem with the OFW theme code.
Best,
Megan
