### ISSUE TITLE
Strange behaviour on <DIV> heights using bean module

### ISSUE THREAD

**Issue by ghost** [SU-SWS/open_framework#198]
I'm using the BEAN module to add blocks. Initially all seemed to be working great. Then I started to notice that on an initial page load each block was a different height. If I then resize the browser all blocks gain equal heights.

When navigating away and returning the blocks are again of unequal heights.

Tested in both Chrome and Firefox.

PS. Forgot to mention this is using a sub-theme of the OFW 2.05 beta.

**Comment by ghost** [comment]
Please see attached images for examples of exppected and unexpected behaviour.

I neglected to mention in my original post that these blocks are inside the 3 column flow region. When placed in the 3 column stacked regions this behaviour doesn't occur. Have now tried with OFW 2.04 and the same happens.

I will try and pick apart my sub-themes css to see if I can pin-point anything there.

In case it's of any help, here is the basic structure of that content region:

row-fluid content-row3
    region region-content-row3 clearfix
        span4 clearfix block block-bean contextual-links-region
            content
                entity entity-bean bean-4-column-block clearfix
                    content
                        (various field classes here)
                            field-item even (this div contains the actual content)

![mangled](https://f.cloud.github.com/assets/650699/1171616/fca651d2-210a-11e3-9e4a-4f1a146107d0.png)
![un-mangled](https://f.cloud.github.com/assets/650699/1171617/03074ad6-210b-11e3-96d4-e83fa8179166.png)

**Comment by hyperboy** [comment]
To achieve equal column height between BEANs in the same row, you can use the block class module and apply class="column" to each of the BEAN.  Make sure you are using OFW 2.06.  Cheers.
