### ISSUE TITLE
Media File Select Pop-up doesn't appear

### ISSUE THREAD

**Issue by OutdoorEd** [SU-SWS/open_framework#201]
I am using the April Release for a new Drupal Commons 3.0 site and find that it doesn’t work with the Media Module (7.x-2.0-alpha2) pop-up windows from the Media File Selector Widget. 

When I click on Select Media to add a file or video link nothing happens. When I change back to Bartik the correct Add File pop-up window appears so I know the issue is theme-related.

**Comment by hyperboy** [comment]
We've implemented a smarter way of doing jquery versioning in our 2.05 beta. Try it out and see if it fixes your problem. https://github.com/SU-SWS/open_framework/releases/tag/7.x-2.05-beta
