### ISSUE TITLE
Revisit accessibility fix on search button

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#202]
From Jennifer:
The search button now reports “search button button” with my screen reader – both with JFW and NVDA.

I think you can just name it “search.” The screen reader knows that it’s a button if it’s got that value.

But, I looked at the code, and it doesn’t look as simple as I it might. I’ll try to figure on it a bit more.

**Comment by meganem** [comment]
Change alt="Search"

**Comment by hyperboy** [comment]
Done - See 870058ae14dd97222b033c6930030f549dd7cc77
