### ISSUE TITLE
Documentation for newbies 

### ISSUE THREAD

**Issue by mpnahar** [SU-SWS/open_framework#203]
Where can I find documentation "user manual" for Open Framework?

**Comment by meganem** [comment]
Documentation is here: https://openframework.stanford.edu

**Comment by SuperClick** [comment]
Hi Meganem,

When I try to check the style "guide section" in https://openframework.stanford.edu

I cannot apply the Filter by Category.

Is it a reflect about all the style available in  open_framework.css located in open_framework-7.x-2.06/css?

Best Regards,

**Comment by meganem** [comment]
Hmm good catch. Looks like that broke since I used it last.
We'll take a look.

The style guide is hand-made, not auto-generated from the code, and no, it's a subset of styles, not all the styles. We'd like to expand on it, but we haven't had time..
