### ISSUE TITLE
Doesn't work with Chosen 1.0.0

### ISSUE THREAD

**Issue by gianku** [SU-SWS/open_framework#207]
I use Open Framework 2.04 and Chosen 1.0.0 for multiple select

There's a conflict with Chosen library:
I select one or more options, then remove from search field clicking on x, but they are unclickable. I select same options and they appear twice.

Why ?

The error (see it with Chrome) is:

Uncaught ReferenceError: test is not defined localhost:8888/SITO/:377
onchange localhost:8888/SITO/:377
b.event.trigger jquery-1.9.1.min.js?v=1.9.1:3
e.event.trigger jquery-migrate-1.1.1.min.js?v=1.1.1:2
(anonymous function) jquery-1.9.1.min.js?v=1.9.1:4
b.extend.each jquery-1.9.1.min.js?v=1.9.1:3
b.fn.b.each jquery-1.9.1.min.js?v=1.9.1:3
b.fn.extend.trigger jquery-1.9.1.min.js?v=1.9.1:4
Chosen.result_deselect chosen.jquery.min.js?v=0.10.0:2
Chosen.choice_destroy chosen.jquery.min.js?v=0.10.0:2
Chosen.choice_destroy_link_click chosen.jquery.min.js?v=0.10.0:2
(anonymous function) chosen.jquery.min.js?v=0.10.0:2
b.event.dispatch jquery-1.9.1.min.js?v=1.9.1:3
v.handle jquery-1.9.1.min.js?v=1.9.1:3

EDIT
If I install the "jQuery update" module then,
Home » Administration » Configuration » Development » jQuery update
In Default jQuery Version I set 1.5 > chosen works fine but toggle of Navbar doesn't work
In Default jQuery Version I set 1.7 > toggle of Navbar works fine but chosen doesn't work

Can someone help me ?

**Comment by hyperboy** [comment]
We've implemented a smarter way of doing jquery versioning in our 2.05 beta.  Try it out and see if it fixes your problem.  https://github.com/SU-SWS/open_framework/releases/tag/7.x-2.05-beta
