### ISSUE TITLE
Revisit reason for including alternative main navigation styles

### ISSUE THREAD

**Issue by hyperboy** [SU-SWS/open_framework#208]
Remove or keep...

/\* navigation -- this is used as an alternative to main menu without the default bootstrap menu styles */
# main-navigation h2 { position:absolute; left:-10000px; }
# main-navigation .content ul li { display:inline-block; }
# main-navigation .content ul ul { display:none; }

**Comment by meganem** [comment]
OK to remove, ID doesn't exist in page template
