### ISSUE TITLE
Find way to support placeholder values cross-browser

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#209]
Don't work in IE9 and others. 

Try:
http://webdesignerwall.com/tutorials/cross-browser-html5-placeholder-textor
or
https://github.com/mathiasbynens/jquery-placeholder

**Comment by meganem** [comment]
We use placeholder on undergrad.stanford.edu in a couple places, in addition to our search form field

**Comment by hyperboy** [comment]
We can add IE specific jquery for search.
