### ISSUE TITLE
Add an external link symbol?

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#214]
Like this: http://www.kaofisis.com/archive/archive_002/archive_002.php
so we can use it?

**Comment by kkasischke** [comment]
May I suggest drupal.org/project/extlink?

**Comment by meganem** [comment]
Thanks Karl! We'll check it out.

**Comment by shanebee** [comment]
I use the External Link module on a number of sites (including some Open Framework ones) and I think it covers external links quite well. I don't think Open Framework needs to address this. (This is me doing the whole "let's not bloat the code" stance.)

**Comment by meganem** [comment]
Sounds good guys. Thanks for the input!
