### ISSUE TITLE
Main Menu other than default Main menu not getting classes applied

### ISSUE THREAD

**Issue by keneim** [SU-SWS/open_framework#216]
I'm using the domain access module with the domain navigation extension module. On the primary domain the main menu works perfectly, but on the subdomain it is not. The dropdown doesn't work, rather the child menu items are listed below the parent in the navigation bar. (See attached screen shots: menu-primary-domain.jpg and menu-subdomain.jpg.)  For the primary domain I'm using the default Main menu as the main menu. For the subdomain I'm using a different menu as the main menu. However, it seems that no menu wokrs properly other that the default Main menu. I've tested this by setting the subdomain's menu as the main menu for the primary domain, and it didn't work there either. 

When I inspect the code with firebug it looks like both have identical markup, until you get to the parent item li tag. There, the Main menu has class=" first expanded dropdown", where the other menu has class=" first expanded active-trial". Correct span classes are not being applied either.

Can you direct me to the code where I might be able to fix this? 

![menu-primary-domain](https://f.cloud.github.com/assets/5025948/1346167/45b66c08-369c-11e3-8c65-e4c7f8582882.jpg)
![menu-subdomain](https://f.cloud.github.com/assets/5025948/1346168/45b80f86-369c-11e3-80b3-6532bfecbfa2.jpg)

**Comment by keneim** [comment]
In the sites/all/themes/open_framework/template.php file, line 541 

I changed

if ((empty($nav_theming_functions)) && (in_array('menu_link__main_menu', $link_theming_functions))) {
    return TRUE;

To read

if ((empty($nav_theming_functions)) && (in_array('menu_link__main_menu', $link_theming_functions)) || (in_array('menu_link__menu_main_other', $link_theming_functions))) {
    return TRUE;
  };

where __menu_main_other is the name of the other menu I wanted classes applied to.  This seems to work.
  };

**Comment by meganem** [comment]
Glad you found a solution. We suggest you subtheme OFW, and copy the menu theme function into your subtheme's template.php file with your fix. Since your fix is specific to your site and the name of your specific menu, we can't roll this out as a general fix.
