### ISSUE TITLE
main menu full width

### ISSUE THREAD

**Issue by marchetb** [SU-SWS/open_framework#218]
Hello,
Firstly congrats for tour work, it's awesome !

I would like to know if there was a way, to make that my main-menu fit the width of the container rather than to be on the left ?

Thanks,
Benjamin

**Comment by meganem** [comment]
Hi Benjamin, can you provide a screenshot as I'm not sure exactly what you're asking. Thanks!

**Comment by meganem** [comment]
There is not a way built-in to OFW CSS to stretch the links to fit the container. You could try using a percentage width for your menu items.
