### ISSUE TITLE
Generate Automatic URL Alias checkbox is enabling Custom URL Alias text field

### ISSUE THREAD

**Issue by hyperboy** [SU-SWS/open_framework#219]
Hi Brian.

When Stanford Wilbur 7.x-2.x (or Open Framework 2.06) is used for content editing, the "Generate Automatic URL Alias" checkbox used with Pathauto on a content edit page is enabling Custom URL Alias text field, which is the opposite of the normal behavior. I have confirmed switching to Seven for content editing makes this behavior return to normal.

I suppose there must be some sort of Javascript conflict, although note this problem has been reported on drupal.org: http://drupal.org/node/1728528

There is currently no known fix, but I'm hoping the discovery it's tied to a particular theme gives people enough of a push in the right direction.

Anyway, do you think you could research why this is happening and/or provide permission to share Wilbur with the module developer so they can debug?

Thanks and regards,

Dan @webdrips

**Comment by meganem** [comment]
Hi Dan,
I think we could consider providing the theme for debugging if you have a developer in mind.
We typically do not recommend OFW (or any of the subthemes) to be used as an admin theme but I'm not sure about your particular use case and what your requirements are. We use Seven for all admin functions and editing content.

**Comment by webdrips** [comment]
Hi Megan.

Unfortunately I'm not sure we have the resources to debug this issue right
now.

I too user a Seven for the admin theme as well, but unfortunately that
provides less of a true WYSIWYG experience.

Regards,

Dan

## 

Dan Harris
Webdrips http://webdrips.com Founder and Chief Engineer
408-821-1631

**Comment by meganem** [comment]
Hi Dan,
We've solved that problem with our existing sites by putting a lot of work into tailoring the WYSIWYG experience so that it reflects the front-facing theme. Unfortunately, getting the WYSIWYG to work right does take some time, but when you can get it working, it is great.
