### ISSUE TITLE
Unable to discriminate sub-links

### ISSUE THREAD

**Issue by SuperClick** [SU-SWS/open_framework#220]
Hello,

Firstly, thanks for your work on this great template. 

In my main top menu, I cannot discriminate if they are sub links or not.

When I load my front page I see this : 
![menu](https://f.cloud.github.com/assets/5969686/1563166/122adc88-505b-11e3-81cc-7e0f4d3e3a00.png)

When I click on the first link , I see this : 
![menu2](https://f.cloud.github.com/assets/5969686/1563168/243cabc2-505b-11e3-9804-6bf9378d3af1.png)

With a little triangle.

I would like to have on the first page the little triangle that informed people about sub links.

I have installed the open_framework-7.x-2.06 version.

You have any ideas ?

Regards,

Adrien

**Comment by meganem** [comment]
Hmm this sounds like a possible problem in your menu configuration. The theme does show the arrow when there are sublinks. Try adjusting the "show as expanded" settings in your top level menu items that contain sublinks.

**Comment by SuperClick** [comment]
Thanks for your response It's exactly what I need.

Adrien
