### ISSUE TITLE
Missing Media Queries

### ISSUE THREAD

**Issue by shanebee** [SU-SWS/open_framework#224]
I have been running into this issue where the media queries break at a certain resolution, specifically between 979px and 1200px.

It doesn't appear to bother all of the sites I have been using Open Framework on (about seven or eight by now) but I do keep noticing that the media queries seem to be not "all there".

According to the Bootstrap 2.3.2 documentation, the responsive media queries are:

```
/* Large desktop */
@media (min-width: 1200px) { ... }

/* Portrait tablet to landscape and desktop */
@media (min-width: 768px) and (max-width: 979px) { ... }

/* Landscape phone to portrait tablet */
@media (max-width: 767px) { ... }

/* Landscape phones and down */
@media (max-width: 480px) { ... }
```

Now, of course, there are some media queries changes for Open Framework documented over here: https://github.com/SU-SWS/open_framework/issues/156

But, how does one deal with these changes? What I have been doing is this, add another media query:

```
@media (min-width: 980px) and (max-width: 1199px) { }
```

This fills in the gap and seems to cure the issues I have been having. I thought it worth a mention here as I haven't found anyone else complaining about the same thing but it may be due to the fact that it only shows up only part of the time, depending on the design of the site.

Of course, there may be something I am missing about the media queries from the modifications made by Stanford.

**Comment by shanebirley** [comment]
Just to clarify what the media queries look like after I update them:

```
/* Large desktop */
@media (min-width: 1200px) { ... }

/* Small desktop */
@media (min-width: 980px) and (max-width: 1199px) { ... }

/* Portrait tablet to landscape and desktop */
@media (min-width: 768px) and (max-width: 979px) { ... }

/* Landscape phone to portrait tablet */
@media (max-width: 767px) { ... }

/* Landscape phones and down */
@media (max-width: 480px) { ... }
```

**Comment by meganem** [comment]
We've documented our media queries here in the new OFW user guide:
https://openframework.stanford.edu/guide/media-queries-code
