### ISSUE TITLE
Can not click on parent item when they have Children 

### ISSUE THREAD

**Issue by cerw** [SU-SWS/open_framework#227]
HI
We have all menu with childern and the parent items also have link, however it's not possible to click on link as the onClick event take over? 

Ta

**Comment by meganem** [comment]
That is not currently an option with Open Framework, or with Bootstrap for that matter. It would take some custom development to enable a second click behavior from the top level menu item. Though I encourage folks to not modify the behavior, as there are usability concerns, particularly across devices, when the top level menu item is a toggle (to open the subitems) and a link.

We believe that the better interaction is to use the top level item as a toggle only, and add an "Overview" link beneath it if you need a landing page for that section.

I hope this helps.
Best,
Megan
