### ISSUE TITLE
cant save structure>block in new subtheme

### ISSUE THREAD

**Issue by vetto-zz** [SU-SWS/open_framework#230]
open_framework-7.x-2.06
Firefox 25.0.1 Windows7

Renamed the extracted directory to just "open_framework", copied out the subtheme_kit up one level into 'themes'.

Renamed the info file, renamed the subtheme directory to match. Enabled both the theme and new subtheme.

Changed the permissions to 644 on the subtheme files (they were 755 in the archive). 

Enabled all the bean modules and context module and block-class module.

When assigning a block to a region (any region), and clicking save, Drupal responds with "blocks saved" but the region is empty still (block went back to the disabled section).  

Nothing in the drupal log.

Copied the templates directory to my subtheme (grasping at straws), didn't help.
Clearly I am doing it wrong.

**Comment by vetto-zz** [comment]
OK. This problem is bean releated I think.  Do I need Bean-All enabled?
With Bean-all enabled, I can position blocks into regions if I exempt them from the "block-type"  in config/system/bean-all (Select Blocks to not appear as Block Types)

Q: Do I need "Bean-all"?
Q: Do I need to use blocks associated with block types (bean) for openframework to function properly?

**Comment by meganem** [comment]
I'm not sure we can help you here, as it doesn't sound like a theme issue. We use BEAN and Context and many other modules successfully regularly with the theme, which is why I don't think this is theme related.
