### ISSUE TITLE
SASSY with SU-SWS / open framework

### ISSUE THREAD

**Issue by Foolevil** [SU-SWS/open_framework#231]
I tried using Drupal Sassy with SU-SWS editing open_framework.info 
stylesheets[all][] = css/open_framework.scss and so. It does not seem to work and is not using scss or sass. Is there something that forces it to use css ?

**Comment by meganem** [comment]
As far as I understand, your server has to be properly configured to handle SASS, and I am not sure it works to just swap it out that way. Typically, the way you would work would be to keep all your scss files in a folder of their own and have them render out to a master.css file which you would want to put in the CSS directory and point your Drupal instance to use.

Hope this helps.
