### ISSUE TITLE
Theme doesn't show up in Drupal

### ISSUE THREAD

**Issue by kinohaitsma** [SU-SWS/open_framework#235]
Hello everyone, I installed the open_framework as advised on my Drupal site; however it doesn't show up in Themes. I installed it in sites/all/themes. In this folder there was already one other theme. The strange thing is that the default themes like Garland are not in that folder, but in the folder themes, one level up. I tried to put the open_framework folder there but still it doesn't show up in Themes. What could I be doing wrong?

**Comment by meganem** [comment]
Hi there, that is strange, as that is the right place to put the theme files. Perhaps try clearing your cache?

**Comment by meganem** [comment]
Perhaps your folder structure got a little messed up, hearing that your other theme files are in a folder one step up. Maybe just double check to match the correct structure and make sure you folders are lowercase, not title case.

**Comment by kinohaitsma** [comment]
Thanks!
