### ISSUE TITLE
Tertiary menus break main menu

### ISSUE THREAD

**Issue by harbingerofdeath** [SU-SWS/open_framework#236]
I've been trying to pinpoint the issue, but I'm not as well-versed in javascript and php as I should be by now. I have tertiary menus for a few pages on my site. When I go to the pages with the tertiary menu block, hovering over the parent menu item within the main menu's dropdown, causes the entire dropdown menu to collapse. 

To clarify:
My main menu's structure is something like this:
Main menu item 1
-Dropdown menu item1
-Dropdown menu item2
--Tertiary menu item 1
--Tertiary menu item 2
Main menu item 2
-Dropdown menu item1
-Dropdown menu item2
Main menu item 3
-Dropdown menu item1
-Dropdown menu item2

In the Drupal main menu settings, Dropdown menu item2 is not set to "expanded" because I don't want it to expand in the main menu; I only want it to show in the sidebar when the related pages are accessed. 

Problem: When I go to Dropdown menu item2's page, the tertiary menu is displayed in the sidebar as it should be, but the parent menu item (in the dropdown menu) shows the expanded arrow (without actually expanding - good) but on hover, the entire dropdown menu disappears/collapses. 

I tried creating a separate menu entirely and only display it on the selected nodes, but then the breadcrumbs no longer display the "trail" - only "Home." 

Any help would be much appreciated! (Besides this prob--awesome theme! TY!)

**Comment by meganem** [comment]
We use Menu Block to control levels of depth to place tertiary menus as sidebar menus on subpages but NOT have them in the main menu. Check it out here: https://drupal.org/project/menu_block also check out our blog series on menu tricks: https://swsblog.stanford.edu/tags/navigation
