### ISSUE TITLE
Fontawesome integration isn't working

### ISSUE THREAD

**Issue by tassoman** [SU-SWS/open_framework#237]
Ciao, I'm trying add some Fontawesome icons but anything comes up.

I've tried injecting jquery code into menus and writing just raw html text into body's node, but nothing happens. <i> tag stills unstyled. Looking at the sourcecode, css looks like correctly loaded.

``` html
 <a href="#"><i class="fa fa-home"></i>Link</a>
```

``` js
jQuery(document).ready(function($){
    $('#main-nav a').prepend('<i class="fa fa-home"></i>');
});
```

**Comment by meganem** [comment]
Hi there,

We are currently only including 3.2.1 of Font Awesome, thus, you'll need to use the old docs:
http://fortawesome.github.io/Font-Awesome/3.2.1/

For info on the included components and their versions in OFW, see: https://openframework.stanford.edu/guide/included-components

In our next release, we'll definitely try to upgrade Font Awesome to the new version.

**Comment by tassoman** [comment]
Ah, huh! Sorry! I wasn't aware of usage modifications between included version and latest library.

Maybe you already know, there is also a https://drupal.org/project/fontawesome module that relies on library module. Maybe could be interesting for your development.

Thanks for helping!
