### ISSUE TITLE
Nav menu item don't show in Nexus5

### ISSUE THREAD

**Issue by ki3104** [SU-SWS/open_framework#239]
Thank you for developing nice base theme.

I would like to pay your attention to the bug I have been facing recently.
1. Summary: 
   When I try to reopen menu on Nexus 5 Google Chrome with Android 4.4.2, 
   I cannot see any contents in menu field. 
   This bug happens only on Nexus 5 Google Chrome with Android 4.4.2
   (I tried this process on iOS, PC browser, and Nexus 7 Google Chrome with Android 4.4.2).

I attached the screenshot . Please check it.
1. How to reproduce this bug: 
   Open a site on Nexus 5 Google Chrome with Android 4.4.2 
   -Open and close the menu
   -Reopen the menu (←You cannot see any contents in menu field)
2. I have no idea why this bug happens. If someone has reported this bug, please let me know the solution.

Thanks.

![screenshot_2014-01-30-13-03-18](https://f.cloud.github.com/assets/1505705/2037749/f1abb7a0-8978-11e3-96f4-6b2cd0d569dd.png)
![screenshot_2014-01-30-13-03-26](https://f.cloud.github.com/assets/1505705/2037750/f90710e4-8978-11e3-974e-682d6472c2ee.png)

**Comment by meganem** [comment]
Thanks for reporting. We don't have a device to test this on... can you run an inspector tool to try and see what's going on in the CSS?

**Comment by meganem** [comment]
Due to inactivity on this thread, and because we don't have the resources to do testing on this, closing.
