### ISSUE TITLE
Site name wraps prematurely in Chrome (Windows)

### ISSUE THREAD

**Issue by hyperboy** [SU-SWS/open_framework#243]
Chrome 33 has an issue with setting the proper width (and height) for divs that use the table-cell display style.

**Comment by meganem** [comment]
not relevant to OFW, moving to SUFW.

**Comment by hyperboy** [comment]
See https://github.com/SU-SWS/stanford_framework/commit/f69bc28385b5c5c9056565ec94aac9eac28c7695
