### ISSUE TITLE
Missing Stylesheet

### ISSUE THREAD

**Issue by justageek** [SU-SWS/open_framework#245]
How do i get the style to look like the demo at
https://drupalthemes.stanford.edu/open-framework"

I have installed the framework, and seem to be missing all the styles.

**Comment by meganem** [comment]
If you've followed the installation instructions, you should not encounter any problems using the theme.
https://openframework.stanford.edu/guide/installing-open-framework

Please post your URL or a screenshot in order for us to take a look, but we have not encountered this as a general bug and is most likely related to how you have installed/set up the theme or your Drupal site/files.

**Comment by justageek** [comment]
Here is our test URL, thanks so much for the help.

_http://test.wttin.org/ http://test.wttin.org/_

**Comment by meganem** [comment]
All the styles seem to show up fine for me.
