### ISSUE TITLE
Please help trouble shoot missing styles

### ISSUE THREAD

**Issue by justageek** [SU-SWS/open_framework#246]
We are using the Open Framework as the base theme for our site.  I cannot determine why the styling doesn't appear to be like the demo site.  My guess is that either missed some files, or, our home page block for announcements just doesn't have the correct markup.  

http://test.wtting.org

I made the sidebars left look like the demo site (gray background) by manually adding the class "well" to the block--sidebar_first.tpl.php file.  I'm not sure if this was the necessary change to make.

**Comment by meganem** [comment]
All your styles seem to be loading fine for me. Classes like "well" are additional modifier classes that let you go further. To add custom styles, either make a subtheme, or use CSS Injector to override OFW styles and add your own CSS code.
