### ISSUE TITLE
Why are there two .container divs in the navbar region??

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#248]
Very frustrating for theming, and I don't know why we have two of these? Is it because Bootstrap requires a "container" div as well?
![screen shot 2014-03-21 at 11 29 47 am](https://f.cloud.github.com/assets/1919260/2486457/ce31a746-b126-11e3-8f8e-5c46340cc5f8.png)

**Comment by hyperboy** [comment]
See https://github.com/SU-SWS/open_framework/commit/cba3309db6637e590a66fd74a48b7b6f01d56542
