### ISSUE TITLE
guide to replicate demo site

### ISSUE THREAD

**Issue by justageek** [SU-SWS/open_framework#253]
I was looking for guidance on how to customize the output of the announcements view / block to look like demo site, with the thumbnails left aligned around the title and teaser.

**Comment by hyperboy** [comment]
Check out the postcard layouts at http://openframework.stanford.edu/postcard-layouts

The code would look something like

``` html
<div class="postcard-left">
   <div><img src="sample.jpg"></div>
   <div><h2>Title</h2><p>teaser text</p></div>
</div>
```
