### ISSUE TITLE
The site_login region missing from the subtheme_kit

### ISSUE THREAD

**Issue by kzoltan** [SU-SWS/open_framework#257]
Since the site_login region missing from the subtheme_kit I get a notice

`Notice: Undefined index: site_login in include() (line 40 of ... page.tpl.php).`

in the subtheme_kit.info.txt the regions should be identical as in the open_framework.info file

**Comment by zchandler** [comment]
Hi Zoltan!

How are things? I don't know if you remember, but we met in Vienna at a Drupal event. Are you still with Reea?

Now for that bug  you discovered. First, thanks! As you know, logging a bug is already a valuable contribution that we appreciate. What we are hoping will happen, especially with developers like you, is that you will feel empowered to fork our repo, and submit pull requests. Engaging with the community in a more open source way is on our list of areas to improve in, and so we're encouraging github forks!

Would you be willing to take a crack at this one, and submit a pull request to the maintainer?

Thanks!
~Zach

**Comment by kzoltan** [comment]
Hey Zach!

Feels good that you still remembered me. It would be a great thing to crack on this.

I have a question: I didn't find this theme on drupal.org, so this is where this came into my mind. Please don't take it personally, its more of a general thought.

Recently I see this trend that people are moving from drupal.org to github, but I am concerned if this will not lead to have even more modules with poor quality without any guaranty if that module is or not secure or obsolete or not maintained.

Would really like to see your point of view on this, what is the default workflow by you.

Bests.
Zoltan

**Comment by kzoltan** [comment]
I just created the pull request. 
Hope its good.
This would be my first one for this :)

**Comment by kzoltan** [comment]
Oh yes and one more unanswered question:
No I just recently switched to another company called Cylex. We are maintaining a business directory across many countries. http://www.cylex-international.ro (Currently working on the relauch of this page )
