### ISSUE TITLE
Submenu not displayed properly

### ISSUE THREAD

**Issue by Biber7** [SU-SWS/open_framework#259]
Hello,
thanks for this very nice theme framework! love working with it.

one problem i realized shows if the menu is displayed in "reduced" (below about 720px width) mode. 
clicking on the menu item opens the submenu but doesn't expand it further. if the submenu has too many entries the submenu isn't displayed properly. if you close and reopen the hole menu once it's working fine.

thanks for support and best regards
Nicolaj

**Comment by meganem** [comment]
Can you tell us which version of Open Framework you are using, your specific browser and operating system? Thanks!

**Comment by Biber7** [comment]
Hey meganem
Sorry - sure:
Framework 7.x-2.06. It happens with every browser and until now it happened on win 7/8, iOS and android.
Thanks and best regards
Nicolaj

**Comment by meganem** [comment]
Is this still happening in the latest release (https://github.com/SU-SWS/open_framework/releases/tag/7.x-2.1)?
Thanks

NOTE: we normally do not have more than one level of dropdown menu items in all the sites we build. It is possible we have not actually tested deeper levels of dropdown behavior. It would help if you do find a bug to take screenshots and of course note specifics in browser and OFW version number.

**Comment by RobWJ** [comment]
hi, i use your theme and i like it :)

i have the submenu problem, but only on iphones ios8 with sfafari. any solutions or workarounds to this problem?
i use 2 submenu levels, and this Drupal Modules:
Special menu items
Menu translation
Menu attributes
The Submenus have as 1. Level <nolink> to open the submenu.

![supportofwsubmenubug](https://cloud.githubusercontent.com/assets/6211267/6616751/a4d8b6b6-c8b1-11e4-9c75-f1563570153e.PNG)

When i click on the Submenus (Produkt,..) nothing happens.

Works all good on Android, Firefox for Android, Windows Mobile Phones!

thx
greetings
rob

**Comment by meganem** [comment]
@hyperboy can we reproduce this error in browserstack?

**Comment by josephgknox** [comment]
@meganem @hyperboy I tested the Open Framework site, which has dropdown menus enabled, on BrowserStack (iOS - iPhone 6, which comes with iOS 8 out of the box) and it works well.

![screen shot 2015-03-12 at 9 10 41 am](https://cloud.githubusercontent.com/assets/8933670/6622197/822e1c32-c898-11e4-9910-8c03f5a21e03.png)

Could the modules that the user has enabled be causing the issue? It doesn't look like we use those modules...

**Comment by RobWJ** [comment]
thx for testing. i try it without the modules and on a fresh install, do nail down the problem.
