### ISSUE TITLE
Adjusting #main-content

### ISSUE THREAD

**Issue by shanebee** [SU-SWS/open_framework#262]
I have a question that I have not been able to answer. What are the best methods for adjusting the #main-content? I am thinking about this for a couple of reasons:
1. Sites that are full width.
2. Sites that may not want to center their main content. What about right or left alignment to the browser window.

It just popped into my mind and am curious what ideas or solutions people have tried?

**Comment by meganem** [comment]
Our theme is based on the Bootstrap-defined widths, so you would need to override those, particularly on the .container elements. Unfortunately we do not have a theme option to change the container/sidebar widths from the GUI.
