### ISSUE TITLE
Ordering Blocks within sidebar at mobile widths

### ISSUE THREAD

**Issue by ToddHollback** [SU-SWS/open_framework#266]
Looking for recommendations on best practice for moving sidebar blocks to appear both above and below content area at mobile widths.  In other words, the theme supports entire sidebar above body content or below body content, but I need a way to show the top sidebar block above the body content and the remaining sidebar blocks below.

Any ideas would be appreciated.

Thanks for all your work on OF!

**Comment by hyperboy** [comment]
Hi Todd,

Here are some options you can try.  You can leverage the flexbox display method to rearrange the content order at different mobile breakpoints. See https://openframework.stanford.edu/content-first-responsive-layout Also check out the "content order in mobile" theme option for showing the main content before the sidebar content.

You can also look at the complex layout demo page to see how you can leverage blocks in the body content region along with the block class module to create the "sidebar look."
https://openframework.stanford.edu/complex-layout
https://www.drupal.org/project/block_class

You'll notice that the element 3 and 6 blocks have the "sidebar look" but sandwiches the element 4 and 5 blocks when it goes to mobile widths.
