### ISSUE TITLE
Could it be possible to include custom css file? 

### ISSUE THREAD

**Issue by jsibley2** [SU-SWS/open_framework#269]
The documentation suggests using css injector to customize css. 

However the Pantheon hosting platform doesn't move these changes from the dev to test to live environments, apparently because they don't transfer the contents of directories called css. 

So, for at least this reason could open framework support using a custom css file, whether or not you require a specific file name and location or allow the user to specify these? 

Thank you.

**Comment by meganem** [comment]
Hi - we have a subtheme package included in Open Framework that is a starter kit for you to make a subtheme. We do not recommend modifying the CSS files or structure in OFW itself, instead we recommend adding your custom layer as a subtheme. Hope this is helpful!
