### ISSUE TITLE
Active Tab according to context

### ISSUE THREAD

**Issue by Asimetrico** [SU-SWS/open_framework#272]
I am trying to activate the tab of the main menu according to the type of content but can not. For example, if we have a blog get each post has the 'Blog' tab enabled.

I'm using the 'Context' module and other templates work correctly. Enabling Open Framework stops working. I understand there are some intereracción-hook that does not allow it work.

I wonder if anyone has 'Context' or another module to get control which menus are active.
Any information or guidance would be greatly appreciated

**Comment by meganem** [comment]
Have you checked with Inspector or Firebug to see when the tab item is active? It may just be that for that particular active state there is missing CSS. If you do in fact find that there is missing CSS for a particular active state, please submit a pull request or another issue with details.

Our team almost always uses Menu Block module and some other nifty tricks. You could check out our blog category here: https://swsblog.stanford.edu/tags/navigation - maybe there is something helpful from a site-building standpoint.
