### ISSUE TITLE
Change when mobile menu kicks in

### ISSUE THREAD

**Issue by jagf** [SU-SWS/open_framework#273]
Hi all,
I would like to change when the mobile menu "kicks in". I would like to move it up one break point from it's current default break point.

If looking at my site (and https://openframework.stanford.edu) on tablet in landscape mode the menu takes up 2 lines. It would be better if it showed the mobile menu.

What file do I need to look at to change this break point?

Testing devices: Nexus 7 2012 and iPad air - current model

Thanks,
Gary
Melbourne

**Comment by meganem** [comment]
Unfortunately there is currently not an easy way to modify this as it is built in to the modified Bootstrap JS/CSS. You can always override any files in the subtheme layer if you want to.
