### ISSUE TITLE
last columns in grid view are bigger than the others.

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#28]
This is happening because the column width is set to 33% but then each column, except the last, has a padding-right of 20px, which re-sizes the content inside. 

One solution is to add back the 20px padding on the last column (easy fix), but this creates perhaps too large of a gap to the right of the body content area.

Not sure, without adjusting the overall width of the table itself, or the body content area how to avoid the extra space between the grid and the sidebar..

**Comment by meganem** [comment]
see this page as example:
https://sites.stanford.edu/csfgs/people/undergraduate-students

**Comment by hyperboy** [comment]
Updated the grid view CSS to the following:

.views-view-grid th, .views-view-grid td {display: inline-block; vertical-align: top; padding: 0 4% 0 0;}
.views-view-grid th:last-child, .views-view-grid td:last-child {padding: 0;}
.views-view-grid img {max-width: 100%; height: auto; width: auto;}
.views-view-grid.col-1 th, .views-view-grid.col-1 td  {width: 98%;}
.views-view-grid.col-2 th, .views-view-grid.col-2 td {width: 47%;}
.views-view-grid.col-3 th, .views-view-grid.col-3 td {width: 30%;}
.views-view-grid.col-4 th, .views-view-grid.col-4 td {width: 21.5%;}
.views-view-grid.col-5 th, .views-view-grid.col-5 td {width: 16.4%;}
.views-view-grid.col-6 th, .views-view-grid.col-6 td {width: 13%;}
.views-view-grid.col-7 th, .views-view-grid.col-7 td {width: 10.5%;}
.views-view-grid.col-8 th, .views-view-grid.col-8 td {width: 8.75%;}
