### ISSUE TITLE
Sub theme - template

### ISSUE THREAD

**Issue by josleow** [SU-SWS/open_framework#280]
Copied subtheme_kit. Then add templates folder with some files that I needed to modify. I noticed that the template files are not overriding the original template files. Is it a bug?

**Comment by jagf** [comment]
I have overriding templates files working, did you clear cache?

**Comment by josleow** [comment]
Yes i kept on clearing cache and nothing happened. I modified the
page.tpl.php with some dummy text and dummy text didnt show up.

**Comment by josleow** [comment]
![screen shot 2015-03-14 at 1 20 06 am](https://cloud.githubusercontent.com/assets/281733/6643585/4b2beccc-c9e8-11e4-8bb3-48b96be7def8.png)

Here is the file structure - I copied subtheme_kit. Not sure why I couldn't see anything.

**Comment by meganem** [comment]
Hi, thanks for the screenshot.
Make sure you follow all the instructions in the README.txt file -- you are missing a step where you need to rename the "subtheme_kit.info.txt" file name in order for your subtheme to register.
Best,
Megan
