### ISSUE TITLE
Unable to remove "No front page content has been created yet" and its link

### ISSUE THREAD

**Issue by josleow** [SU-SWS/open_framework#281]
I tried in subtheme's page--front.tpl.php with only blocks: 

function themename_preprocess_page(&$variables) {
    if (drupal_is_front_page()) {
       unset($variables['page']['content']['system_main']['default_message']);
       //will remove message "no front page content is created"
       drupal_set_title(''); //removes welcome message (page title)
     }
  }

But text still persists.

How do I remove  "No front page content has been created yet" and its link

**Comment by meganem** [comment]
Hi Josephine,
This is not an issue with the theme, more just a thing to know about Drupal. You need to create a page and set it to be your homepage by going to Config > System > Site Information.

For the future, please try to only use the issue queue for posting bugs and suggestions related directly to the OFW theme. Thanks!

**Comment by shanebee** [comment]
Just a quick note to josleow, you can either promote content to the front page or you can use this module (there are a couple of others but this one is the simplest) to remove the message.

https://www.drupal.org/project/empty_front_page
