### ISSUE TITLE
Discrepancy between JS width and BS breakpoint

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#287]
At the 979 breakpoint in BS, the second sidebar is "off" slightly in the Javascript override file in OFW.
![screen shot 2015-07-09 at 2 11 03 pm](https://cloud.githubusercontent.com/assets/1919260/8606977/821dcd50-2644-11e5-9507-82329701448c.png)

**Comment by meganem** [comment]
Can test here:
https://openframework.stanford.edu/regions/right-sidebar
The second sidebar hangs around for like 5-10px more than it should, all squished.

**Comment by hyperboy** [comment]
The scrollbar width is the culprit in the viewport width discrepancy.  See http://www.sitepoint.com/rwd-scrollbars-is-chrome-better/
- Chrome and Safari exclude the scrollbar dimensions
- Firefox, Opera and IE include the scrollbar dimensions

**Comment by meganem** [comment]
I've patched this in CSS on the CAW site using the following:

```
@media (max-width: 979px) and (min-width: 960px) {
 .sidebar {
  clear: both;
   display: block;
   width: 100%;
 }
  .sidebar .block {
   width: 31.4917%;
    display: inline-block;
    vertical-align: top;
    margin-right: 2.76243%;
  }
  .mc-content {
    width: 100%;
  }
}
```
