### ISSUE TITLE
When a mix of well and not well blocks, column class calculates incorrectly

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#289]
e.g. https://sites.stanford.edu/caw/
![screen shot 2015-07-15 at 11 53 35 am](https://cloud.githubusercontent.com/assets/1919260/8707040/283de9a2-2ae8-11e5-91df-00e6176656bf.png)

**Comment by hyperboy** [comment]
Since the padding will be off even when the height calculates correctly, creating a "non-well" class that simulates the "well" class but without the background color would work.  This way, the headings will still still align properly.

**Comment by hyperboy** [comment]
Added "non-well" class.  See https://github.com/SU-SWS/open_framework/commit/27ec16128205078ce8701fd2b88096a4cb9a7773

**Comment by hyperboy** [comment]
I will be adding the "non-well" example to https://openframework.stanford.edu/equal-block-height once the style is published.
