### ISSUE TITLE
Still problem with clear-row class at certain breakpoints

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#290]
we seem to be losing margins on blocks that have the clear-row class at certain breakpoints.
I don't think this was introduced in our recent bug fix, but it is related.

https://openframework.stanford.edu/regions/no-sidebars

<img width="673" alt="screen shot 2015-07-17 at 3 44 06 pm" src="https://cloud.githubusercontent.com/assets/1919260/8758671/6f86ae3e-2c9b-11e5-9615-d1b4bd51fed2.png">

**Comment by meganem** [comment]
Actually, this seems to be a problem with layouts where we intersperse a span12 block with other blocks and break the odd/even targetting of blocks. Because the span12 block then resets the odd/even.

I don't know how we would fix this really...

**Comment by hyperboy** [comment]
See c3f5db0e7ae28b6fde0607850deddeec817bd240

**Comment by hyperboy** [comment]
![capture](https://cloud.githubusercontent.com/assets/716099/11230358/17cf08f8-8d53-11e5-8054-f51d771eec5b.PNG)

**Comment by hyperboy** [comment]
![capture](https://cloud.githubusercontent.com/assets/716099/11230370/367e0e34-8d53-11e5-8f94-7c7c4819d0cc.PNG)
