### ISSUE TITLE
span12 and clear-block class in content-field.tpl.php

### ISSUE THREAD

**Issue by jbickar** [SU-SWS/open_framework#3]
Can you revisit the default assignment of the .span12 and .clear-block classes for CCK fields? On CCK nodes with many fields, it makes it difficult to reposition them using solely CSS.

Ref: https://sites.stanford.edu/physics/people/faculty/robert-b-laughlin

**Comment by hyperboy** [comment]
Not a problem, I'll remove the bootstrap .span12 and .clear-block classes for CCK fields for now.
