### ISSUE TITLE
Output site title in HTML

### ISSUE THREAD

**Issue by jbickar** [SU-SWS/open_framework#37]
The current implementation of using custom logos as the site title requires unchecking the "site title" at admin/build/themes/settings. This causes the site title not to be output in the HTML of the page, which presents a usability and accessibility issue.

Suggested solution: output the site title as in Stanford Modern, but hide with CSS, e.g.,:
    &lt;div id="site"&gt;
    &lt;div id="name"&gt;
        &lt;a href="/"&gt;Awesome Site Name&lt;/a&gt;
    &lt;/div&gt;
    &lt;/div&gt;

**Comment by meganem** [comment]
i.e. when I am not showing the site title, just a logo, we need the site title text to also render but be hidden on the page. Make this dependent on the "logo only" theme option.

**Comment by meganem** [comment]
Hi John,
Right now, here is how we are rendering the site title. Is this structure OK, or should I modify it to match the structure you suggest?

![Screen Shot 2013-03-20 at 8 57 29 AM](https://f.cloud.github.com/assets/1919260/281411/e750d83a-9176-11e2-9ce4-291706f6fa2d.png)

I have this working on tbdemo:
https://sites.stanford.edu/tbdemo/

In Wilbur theme settings, uncheck site title and slogan, and you should see the hidden site title rendering next to the logo div.

Let me know what you think about the code structure naming. I'd like only one convention that we implement in both cases.

**Comment by jbickar** [comment]
I think this is good. The main issue we want to solve for is providing text in the HTML for text that we have in an image (e.g., a logo image), and this does that.
