### ISSUE TITLE
region_has_block not returning correct result

### ISSUE THREAD

**Issue by mistermarco** [SU-SWS/open_framework#6]
In template.php, region_has_block() doesn't seem to respect whether a user has permission to actually see a block in a region. For example, if you add a block to the right sidebar, but make it visible to just authenticated users, it'll return 1 for anonymous users as well, even though it should return 0.

How about we use count(block_list($region)) instead?

**Comment by mistermarco** [comment]
Something along these lines...

```
function region_has_block($test_region) {
  $number_of_blocks = count(block_list($test_region));
  if ($number_of_blocks > 0) {
    return TRUE;
  }
  else {
    return FALSE;
  }
} 
```

**Comment by mistermarco** [comment]
We also probably don't want to call it more than twice per template (once for each of the left and right regions in the template), and rename it?

**Comment by hyperboy** [comment]
Good catch!  I'll test it out your suggestion locally.
