### ISSUE TITLE
Figure out how to apply bootstrap btn class to all form input submit buttons

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#61]
default drupal buttons are not styled well. can we take advantage of Bootstraps btn class by adding it to the theme layer so it gets added to all inputs?

or do we need to duplicate bootstraps code for the btn class and apply to the form-submit class?

**Comment by meganem** [comment]
Tested code out: 

/\* Add btn class to all form submit buttons */
function open_framework_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id) {
    $form['basic']['submit']['#attributes']['class'][] = 'btn';
  }
}

/*function ofw_views_exposed_form($form, &$form_state) {
    $form['#attributes']['class'][] = 'my-form';
    if ($form['#id'] == 'views-exposed-form-views-test-page') {
        $form['actions']['#attributes']['class'][] = 'btn';

```
}
```

}*/

The first part works for search form buttons. Can't figure out how to get this added to views exposed form buttons, or all buttons. Might need to use javascript to do this, or re-create the Bootstrap btn class on the class that Drupal adds by default.

**Comment by Codelica** [comment]
Just a note that native Bootstrap form buttons (and other elements) could be pulled from this issue/commit:

https://github.com/SU-SWS/open_framework/issues/83
