### ISSUE TITLE
Sprite or pre-load images in base theme

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#62]
For example, more-link... any others? or can we replace more-link with a character in the CSS content?

**Comment by randyfranklin** [comment]
Depending on GSB upcoming design, I was thinking of doing our social icons as a sprite. Would be nice to have these as part of base theme because bootstrap icon set does not include social if I recall...

Facebook ("f")
Twitter ("t" and "bird") 
Pinterest
etc...

We could have square, circle, and transparent for each icon potentially..

**Comment by meganem** [comment]
Great idea. No, TBS does not have social media icons in their set. Their icons are also very low res and not helpful except at tiny size, so yes, brainstorming what other icons we might want in there and spriting those up together would be good. 

Send me any specific ones you like! I have a set that came with our Rolling Orange designs, but I want to re-think these, and probably choose a set that matches more with OFW style (at least with OFW). Then you could override with an altered PNG file or whatnot.

**Comment by randyfranklin** [comment]
Definitely, I'll check out what is coming down the pipe from our design comps and see if there are some common general patterns that are best to include for OFW.

**Comment by Codelica** [comment]
You might want to check out the Font Awesome project:

http://fortawesome.github.com/Font-Awesome/

A much superior (vector) set that is designed to integrate with TBS and contains social icons among other things.  Integration can either be done with a single CSS inclusion (simple) or by making a custom Bootstrap via LESS (optimized).  Instructions are on the page.

Might be a nice "option" in the theme preferences.. ;)

**Comment by meganem** [comment]
We removed hover images and added font awesome in V1, so closing this.
