### ISSUE TITLE
Need default responsive behavior for tables

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#64]
Right now, tables do not respond. We should consider a default responsive behavior for tables.

**Comment by ToddHollback** [comment]
Just wondering if this issue has been addressed since Nov 2012?

Bootstrap 3 includes the table-responsive CSS class, which may be a quick fix.

**Comment by hyperboy** [comment]
We have not addressed the responsive table issue.  We're looking at embedding Bootstrap 3 in the 7.x-3.0 release of Open Framework.

In the meanwhile, here are some CSS/JS solutions that help with crafting different kinds of responsive tables.
- http://css-tricks.com/responsive-data-table-roundup/
- http://zurb.com/playground/responsive-tables

**Comment by meganem** [comment]
Probably not a theme-wide setting. Instead you might want CSS Injector to target specific tables...
