### ISSUE TITLE
Remove need for clear-row class on blocks

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#66]

**Comment by sohananktech** [comment]
Go to templates folder and edit block.tpl.php file and remove class from block.

**Comment by meganem** [comment]
This is changing the default responsive behavior to know when blocks should be forced to a new line. This is when you are using span overrides to get a custom block layout, as seen at https://openframework.stanford.edu/regions. Blocks that start a new line in a custom block configuration need a clear-row class to force them to start a new line.

I am not sure this is something we can easily resolve, so moving it to V2.

**Comment by meganem** [comment]
probably not for D7
