### ISSUE TITLE
Fix listing order of regions in blocks page to be consistant with content viewing order

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#67]

**Comment by hyperboy** [comment]
Updated open_framework.info

regions[header] = Header
regions[navigation] = Navigation
regions[search_box] = Search Box
regions[main_top] = Main: Top
regions[main_upper] = Main: Upper
regions[sidebar_first] = First sidebar
regions[highlighted] = Highlighted
regions[help] = Help
regions[content_top] = Content: Top
regions[content_upper] = Content: Upper
regions[content] = Content: Body
regions[content_row2] = Content: 2-column flow
regions[content_col2-1] = Content: 2-column stacked (1)
regions[content_col2-2] = Content: 2-column stacked (2)
regions[content_row3] = Content: 3-column flow
regions[content_col3-1] = Content: 3-column stacked (1)
regions[content_col3-2] = Content: 3-column stacked (2)
regions[content_col3-3] = Content: 3-column stacked (3)
regions[content_row4] = Content: 4-column flow
regions[content_col4-1] = Content: 4-column stacked (1)
regions[content_col4-2] = Content: 4-column stacked (2)
regions[content_col4-3] = Content: 4-column stacked (3)
regions[content_col4-4] = Content: 4-column stacked (4)
regions[content_lower] = Content: Lower
regions[content_bottom] = Content: Bottom
regions[sidebar_second] = Second sidebar
regions[main_lower] = Main: Lower
regions[main_bottom] = Main: Bottom
regions[footer] = Footer
