### ISSUE TITLE
js error

### ISSUE THREAD

**Issue by peterm95018** [SU-SWS/open_framework#70]
First, thanks Stanford. I had found this project and pulled a D7 version back in mid-Oct. It's been working fine on my laptop. I've been working on a new version of the campus map for UC Santa Cruz. http://maps-dev-d7.ucsc.edu

I pulled a fresh copy today and am now receiving the error: 
`Uncaught TypeError: Object [object Object] has no method 'on'   bootstrap.min.js 6`

You'll aslo note that it looks like the js for the #main-menu dropdown-toggle appears to be firing twice. 

I've spent a few hours looking for module conflicts and am not finding anything obvious. If someone can point me in the right direction, I'll put some more time into debugging and report back.

Peter

**Comment by hyperboy** [comment]
Peter,

Thank you for using Open Framework for your site.  I'm sorry you've spent hours looking for module conflicts.  Rather than pulling the latest changes, you may want to use the 7.x-2.0 tagged release instead.  https://github.com/SU-SWS/open_framework/tags

I've recently merged some javascript code to accommodate sites that are using the jQuery update module.  It might be breaking something in the theme.  I'll take a look and troubleshoot it this week.

Brian

**Comment by sherakama** [comment]
Brian is right. With the latest update the include jquery.js file was changed to offload to jquery_ui module as per drupal best practices and conventions. This means that any js code that was using the naked $.('.select').dosomething(); code will no longer exist. You will have to wrap your custom functions in the jquery wrapper.

(function ($) {  
  // Your code here
})(jQuery);

see http://drupal.org/node/756722 for more information.

Cheers,

**Comment by zchandler** [comment]
Hi Peter, How cool that you are using our theme! So glad that it's been useful ... umm, until it started throwing errors that is :) 

Hopefully Sherakama has the fix. (Thanks Shea!)

We are also have another project under development that will hopefully break some ground on how to do responsive theming specifically for map interfaces, so stay tuned!

Cheers,
Zach

**Comment by peterm95018** [comment]
Thanks folks. I'll reset my dev environment. Let me know if there's anything I can do to help. 

BTW, this is fixed. Also needed to add this tweak for OpenLayers to work:
`.openlayers-views-map img {
  max-width: none;
}`

Peter

**Comment by gitressa** [comment]
I was getting the same error after substituting the included jQuery version in OFW with the jQuery Update module, to be more future proof. But the current official release only updates jQuery to 1.5. So I had to install the dev version (7.x-2.x-dev) of jQuery Update, and then I could select which version of jQuery to use, under admin/config/development/jquery_update, which updates it to jQuery 1.8.2 and jQuery UI 1.8.11

It would be really awesome to see this great theme on drupal.org soon!

**Comment by meganem** [comment]
Thanks for the really nice feedback! We are so thrilled that everyone is participating in the conversation and development. Keep it coming!
