### ISSUE TITLE
Regions resize

### ISSUE THREAD

**Issue by nchicong** [SU-SWS/open_framework#72]
Hi team,

This Open Framework is great. Awesome combination of Drupal 7 and Twitter Bootstrap. I'm trying it out.
I'd like to ask a feature request for region resize. For example, I need to make #second-sidebar to be span4 and #content to be span 8. Something like Omega theme where I can choose how many columns for the region.

I attempted to override by removeClass(), addClass() but script.js keeps bugging.
Thanks.

**Comment by meganem** [comment]
Thanks for the note! We've actually implemented this in a subtheme, where we changed the spans of the sidebars to span4 each and content area is span8 or span4 depending on how many sidebars are activated, so it is possible. 

We would need to look into what it would take to make this a theme option. I would imagine a "Enable wide sidebars" checkbox in the theme settings.

**Comment by nchicong** [comment]
That sounds great. That theme option can help me to use delta separately for Home and other pages.

Instead of making a subtheme just for 1 page, do you have any suggestion for a quick tweak to have span4 for #second-sidebar on Homepage. 
I googled ways to detect what current context is but not succeeded.

Thanks.

**Comment by hyperboy** [comment]
I think this is a pretty common request.  What we can do is have two page templates:  page.tpl.php and page-front.tpl.php.  We can then allow users to choose different sidebar widths in the theme options for the two page templates.  It's not a high priority since there are other more urgent bugs to tackle.  We'll keep you posted.

**Comment by nchicong** [comment]
Yes it will be great if user can specify wide side bar in one-sidebar and two-sidebars. Currently I'm handling this by having span4 sidebar in home with combination of page--front.tpl.php & "if ($('body').hasClass('front'))" in script.js. Looking forward to hearing enhancement in OpenFramework.

Cheers.

**Comment by shanebee** [comment]
I see there isn't anything in the settings yet (just installed and updated several web sites with v2.1) and wanted to pass along what I have been doing to adjust the default widths of these columns. I think of this as more of a stop gap should anyone want to adjust these widths manually.

## How To Adjust Column Widths (The Hacky Way)

First off, the class defaults for "sidebar-first", "content", and "sidebar-second" are: span3, span6, and span3. The middle column adjusts the class setting based on whether or not the sidebars are in use. This means we need be sure that any adjustments we make don't mess with the middle column. In the example below, I am going to make the sidebars more narrow while increasing the size of the middle column.

### What To Change

**Sidebar First**

> div id="sidebar-first" class="sidebar span3 site-sidebar-first"
> _to_
> div id="sidebar-first" class="sidebar span2 site-sidebar-first"

**Content**

> div id="content" class="mc-content <?php if (($page['sidebar_first']) && ($page['sidebar_second'])): print 'span6'; elseif (($page['sidebar_first']) || ($page['sidebar_second'])): print 'span9'; else: print 'span12'; endif; ?>"
> _to_
> div id="content" class="mc-content <?php if (($page['sidebar_first']) && ($page['sidebar_second'])): print 'span8'; elseif (($page['sidebar_first']) || ($page['sidebar_second'])): print 'span9'; else: print 'span12'; endif; ?>"

**Sidebar Second**

> div id="sidebar-second" class="sidebar span3 site-sidebar-second"
> _to_ 
> div id="sidebar-second" class="sidebar span2 site-sidebar-second"

Once you make this change, the span classes will take over and the widths will adjust. You can, of course, use different span calls. Just make sure they are all equal to 12 and you should be good.

And do let me know if I have missed an easier path to changing the widths. I have been adjusting them this way for a while (when I am using the default sidebars) and it works just fine.

**Comment by shanebee** [comment]
I forgot to mention that you also need to adjust the override.js because if the script doesn't find the appropriate class name, it will double the classes, of course overriding the class changes above.
