### ISSUE TITLE
Depend on jquery_update.module

### ISSUE THREAD

**Issue by cweagans** [SU-SWS/open_framework#75]
Themes shouldn't ship their own version of jQuery (even if it's included in compatibility mode) because it results in two versions of jQuery being parsed on every page, which is not a good thing. Instead, you should depend on jquery_update being installed.

**Comment by hyperboy** [comment]
Thank you for submitting the issue.  We'll look into adding the jQuery Update module (7.x-2.x-dev) as a theme dependency in a future theme update.

**Comment by redndahead** [comment]
I'll second this.  While I don't believe you can make a module a dependency of a theme it would be great if this could be removed as it breaks our sites.

**Comment by rupl** [comment]
That's correct, theme dependencies are not possible in Drupal 7. However, you're free to put a warning in template.php or `open_framework_install()` that checks for jquery_update via `module_exists('jquery_update')`

**Comment by hyperboy** [comment]
Thank you for all the feedback on the multiple jQuery call issue.  We've decided to use a jQuery replacement method in template.php to replace jQuery 1.4.4 with jQuery 1.9.1 on non-administration pages.  See https://github.com/SU-SWS/open_framework/issues/108
