### ISSUE TITLE
Fix legend styles

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#79]
I have noticed that legend elements over-run each other when they are collapsed.   I had same problem with one of my other sites, so  I have added these three styles for legend

legend {

```
font-size: 16px;
margin-bottom: 1em;
line-height: 1.6em;
```

}

original code in bootstrap
legend {

```
display: block;
width: 100%;
padding: 0;
margin-bottom: 20px;
font-size: 21px;
line-height: 40px;
color: #333;
border: 0;
border-bottom: 1px solid #e5e5e5;
```

}
- Irina

**Comment by irinaz** [comment]
Hi, 
Do you know if these two changes are in the most current version of Open Framework?
thanks, Irina

html.js fieldset.collapsed {
 height: auto;
}

**Comment by meganem** [comment]
Since we haven't closed this ticket, then no, they haven't been rolled into OFW yet.

**Comment by irinaz** [comment]
overlapping button and collapsed fieldset title (https://f.cloud.github.com/assets/2497005/1770056/24d1f6f0-6780-11e3-9dd1-e1b36b37f22b.png)
collapsed fieldset title with new styles (https://f.cloud.github.com/assets/2497005/1770054/24d17eb4-6780-11e3-8c13-39942a96f097.png),  (https://f.cloud.github.com/assets/2497005/1770055/24d1aa60-6780-11e3-8958-3ef6e7a85373.png)

Thanks!

Maybe we can then use this change in tomorrow's workshop to see what is 
best way to work with user's submitted code.

Thanks, Megan!
