### ISSUE TITLE
Grid View tables cause responsive layout issues

### ISSUE THREAD

**Issue by jbickar** [SU-SWS/open_framework#8]
https://sites.stanford.edu/physics/resources/forms and https://sites.stanford.edu/physics/research are Views that use the "Grid" display style. This style uses tables to output content in a grid format; these tables overflow into the fat footer area at certain break points in the responsive design.

**Comment by hyperboy** [comment]
The grid view should really use divs instead of tables for page layout.  I'll look through other Drupal base themes and modify the views-view-grid.tpl.php to use divs for layout.

**Comment by hyperboy** [comment]
I've added responsive styling for the grid views tables.  However images now do not respect views grid table widths in certain browsers like Firefox.  See logo section at the bottom of the https://sites.stanford.edu/csfgs/ front page.

**Comment by meganem** [comment]
fixed with FF14
