### ISSUE TITLE
Patch: Separating styles and add ability to disable

### ISSUE THREAD

**Issue by oresh** [SU-SWS/open_framework#80]
Please see patch below against latest 7.x-2.x.
It provides possibility to disable navigation styles if needed in theme settings. 

https://raw.github.com/gsbitse/gsb-revamp-patches/master/sepearate-nav-styles.patch

**Comment by hyperboy** [comment]
Thanks for submitting the patch for the top nav!  We'll review and incorporate accordingly.

**Comment by oresh** [comment]
Thanks. Please make sure you add patch -p1 when patching.

**Comment by hyperboy** [comment]
I've started the 7.x-2.x-dev branch to test out your patch, but I've hit a roadblock in applying the patch from https://raw.github.com/gsbitse/gsb-revamp-patches/master/sepearate-nav-styles.patch .  I kept getting the "Patch format detection failed" error message.  I've also tried various git commands like -p, apply, and am without success.

Is it possible to recreate the patch file using the git format-patch command?

Here are some best practice documentation on git patches.
http://www.cloudspace.com/blog/2010/07/14/patching-with-git-format-patch-and-git-am/
https://wiki.documentfoundation.org/Development/Patch_Handling_Guidelines

**Comment by oresh** [comment]
For the patch - i think i'll have to rethink it.
The problem is that i separeted styles in the bootstrap.css file and thats
not the best idea. I need to figure out, how to separate those styles
without breaking the bootstrap thingy.

So you'll have to wait a bit, till i figure out how to do this and how to
make theme settings apply. I'll write you as soon as i'm finished

**Comment by meganem** [comment]
Closing this issue as I am not sure you are still planning to do this?
