### ISSUE TITLE
.summary class

### ISSUE THREAD

**Issue by Codelica** [SU-SWS/open_framework#81]
Hello!

I'm all for keeping Open Framework as a minimalist Bootstrap base theme, but there is one class (.summary in open_framwork.css) that gets picked up by Drupal's vertical tabs and may be worthy of an override:

Currently due to .summary with font-size: 22px : 

![vert-tabs](https://f.cloud.github.com/assets/386101/140551/fe60028e-7223-11e2-8269-c20023948f67.jpg)

Just adding div.vertical-tabs .summary with font-size: 12px; :

![vert-tabs-2](https://f.cloud.github.com/assets/386101/140567/e8f8e91e-7224-11e2-885c-99975d8f88a3.jpg)

Nit picking, I know ;) 

Also just an FYI that Bootstrap 2.3 is out now, which (from what I've seen) seems to fix some nagging issues with dropdown/submenus on mobile/touch devices.  At least it fixed the issue I was having.  I believe it was also prepared with jQuery 1.9 as well.

Thanks for your work on OF... :+1:

**Comment by meganem** [comment]
Awesome! Will do. Thanks for the head's up!

**Comment by meganem** [comment]
That was supposed to say fix.
