### ISSUE TITLE
(global nav) ul.menu.nav li.expanded.dropdown change in behavior

### ISSUE THREAD

**Issue by petechen** [SU-SWS/open_framework#82]
I noticed that the most recent change with bootstrap relegates the hyperlinking function to a parent item in the global nav dropdown inactive.  I understand that this happens as now these menu items inherit/acquire the "dropdown" class function from bootstrap and now function as a toggle for dropdown-toggle.  

This was a little disruptive as the parent items were originally set as functioning URLs.  Once I got the hang of this change, it was OK but I think it opens up a slight UX issue that users don't understand right away that the menu parent shouldn't function as a destination. To remedy this, I'd suggest giving  #main-menu ul.menu.nav li.expanded.dropdown a.dropdown-toggle (and li.expanded.dropdown.open a.dropdown-toggle) a different treatment from #main-menu .navbar .nav.li a.  (i.e. make the parents of dropdown menus distinct from other linked global nav elements besides just the carat).  

One possible solution (that I'm still experimenting with in my subtheme) is what I'm developing at https://icme-dev.stanford.edu (Stanford only, sorry).  I'm not 100% with the idea and it'll likely evolve more in a day or two but fading back the parent seems to make it a little more clear that when expanded, users should not expect it to function like a link.

**Comment by meganem** [comment]
Hey Pete,
Yes, we definitely understand this UX problem. I like your solution with a different treatment for those kinds of links. The way the drop-down menus are behaving is not ideal, but it is the best compromise we could come up with to deal with touch devices etc. Brian can go into a little more detail about this probably as he was the one implementing the menu behavior.

In general, this is something we need to document better and propose solutions like the one you have implemented. Thanks for sharing. Any other suggestions are welcome.

**Comment by meganem** [comment]
Closing this issue. In regards to the above thread, an update:

Right now, dropdown menu items that have nested items act as a toggle only on click. They do not link to a page, instead open the drop-down menu on click. The reason we went this way is to have a consistent mobile and desktop experience. On mobile, hover is equivalent to click, and when you click an item with a dropdown, the dropdown menu would appear. On mobile, it is very hard to have a dropdown menu appear AND have the top link act as a link. We found this to cause some serious UX and navigation problems (where sometimes the link works, and sometimes it opens the dropdown), so we decided to implement a simplified desktop and mobile solution where the parent item only acts as a dropdown toggle and does not link to a page. This way, the mobile experience always works, and is consistent with the desktop experience.

We are now working on a way to manually control when the Bootstrap dropdown behavior classes are added to a menu. This is tracked in a separate issue.

**Comment by petechen** [comment]
Thanks Megan!  

So the expected behavior affects the menu system by disabling links from the primary nav element once a secondary menu item(s) is established.  It's a bit different way of thinking IA wise (and affects the weight given to landing pages) but I understand the reasoning.  I'd prefer to actually disable this functionality at will, which I could do in my subtheme but am a bit concerned about carrying over through future updates.  For now, I might roll back OF to previous bootstrap functionality. 

At this point, this is probably more an issue to take up at the bootstrap level.

**Comment by meganem** [comment]
Yes, you've got it right.

What we are working on now is a way to set in the theme options which menus are effected by the Bootstrap behavior. If you set none to be effected, then you can apply your own behaviors or use Drupal's default behaviors. We are hoping this will be included in the upcoming theme release at the end of March.
