### ISSUE TITLE
Native Bootstrap buttons, checkboxes, radios, etc...

### ISSUE THREAD

**Issue by Codelica** [SU-SWS/open_framework#83]
Hello,

I wasn't really sure about the etiquette surrounding pull requests, but I commited a few changes to a fork of open_framework that you may want to consider:

**Native Bootstrap button class**

Sets "btn" class on form buttons (via preprocess function) for native Bootstrap buttons.  Removes Open Framework button CSS.

**Native Bootstrap Radio buttons & Checkboxes**

Sets "checkbox" and "radio" class wrappers for native Bootstrap checkboxes and radio buttons. It wasn't possible to add proper Bootstrap style wrapper classes via a preprocess function since core's theme_form_element() re-sets the class array. :(  So I added a #post_render call rather then overriding core's theme_form_element() (which seemed extreme considering we are just adding a class).

**Apply Bootstrap "block-level" class to form text inputs** (optional theme setting, default off)

This allows text inputs to span the full container width, like you see in the veritcal tab sections of node forms.  Basically if enabled, this:

![text-fields](https://f.cloud.github.com/assets/386101/165709/c8ab5358-7969-11e2-9d39-4692b20f27c3.jpg)

Becomes:

![text-fields2](https://f.cloud.github.com/assets/386101/165710/e12c819a-7969-11e2-87f3-815b1a8f0e9d.jpg)

**Apply Bootstrap button classes (primary, info, warning, etc.) to form buttons** (optional theme setting, default off)

I kept this optional also, but I find the Bootstrap button classes can really help seperate/define common form actions.  Basically if enabled, this:

![buttons](https://f.cloud.github.com/assets/386101/165711/ec61266a-7969-11e2-93e0-53f0abcb6ca8.jpg)

Becomes:

![buttons2](https://f.cloud.github.com/assets/386101/165712/f4f1d36a-7969-11e2-8ab9-f0e4ac7ae689.jpg)

You can ignore the alignment/floats/margins here, that's just from a sub-theme. (I don't like delete buttons by submit buttons :) )

This stuff is all in this commit:

https://github.com/Codelica/open_framework/commit/8df2782f785f96dd3efd0b2f74fe9105d212707c

I think it's worth considering, as the closer things are to native Bootstrap classes the easier it is for people to make use of pure Boostrap themes (Bootswatch, Wrapbootstrap, etc)

I'm also working on overriding the Drupal vertical tabs for mobile (phone) widths, as they just don't make sense.  (Most likely having it revert to a finger-friendly accordian, similar to what they were looking at in Drupal 8.)

Well, that's it.  Thanks for reading...

-James

**Comment by hyperboy** [comment]
Thank you for the Bootstrap integration suggestions.  We'll review https://github.com/Codelica/open_framework/commit/8df2782f785f96dd3efd0b2f74fe9105d212707c and incorporate the appropriate changes into the main branch.  We'll keep you posted.
