### ISSUE TITLE
"IE Fix for HTML5 Tags" generates security warning on Win7/IE8

### ISSUE THREAD

**Issue by jbickar** [SU-SWS/open_framework#84]
templates/html.tpl.php, line 15, reads:

  &lt;script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"&gt; &lt;/script&gt;

That should use https protocol.

**Comment by rwinikates** [comment]
Actually it should use a protocol-less reference, as that is the [Google suggested best practice](http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml#Protocol):

```
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"> </script>
```

**Comment by hyperboy** [comment]
Wow, this is great!  I didn't realize it's possible to omit the http or https protocol in embedded resources.  Thanks!

**Comment by jbickar** [comment]
Yeah, that's awesome, thank you very much.
