### ISSUE TITLE
Break CSS into multiple files that are more easily traced/organized

### ISSUE THREAD

**Issue by meganem** [SU-SWS/open_framework#91]

**Comment by oresh** [comment]
Now that i look at the CSS, i think we can just separate the colors into color.css file
and maybe responsive also move to media-query.css file. This can be enough.

**Comment by oresh** [comment]
Actually, if we move the media query selectors into separate css file, we can make a fallback js to check for the browser and add a css file for specific window width, like screen-size-800.css or something. with no media queries and CSS3 selectors inside it, so we can make responsive support in IE8 and 7.

**Comment by meganem** [comment]
That sounds good! Probably not going to happen for V1, but definitely for V2.
